### ISSUE TITLE
Support Vanity URLs

### ISSUE THREAD

**Issue by trieloff** [adobe/theblog#133]
When blog posts are used in non-web promotions, it is desirable to provide a vanity URL, i.e. instead of using https://theblog.helix-demo.xyz/ms/en/archive/2020/36-days-of-type-participate-for-a-chance-to-win.html an author might prefer https://theblog.helix-demo.xyz/win36type

The authoring experience should be as simple as adding a line like

```markdown
Published on Feb 27 2020
Posted by Lars Trieloff
Available at https://theblog.helix-demo.xyz/win36type
```

to the bottom of the page in Word or Google Docs.

**Comment by trieloff** [comment]
## Possible implementation (`theblog` only):

- add a new property `vanity` URL to the index (filter)
- create a `404.html` that queries the index for `vanity==window.location.href`
- if there are results, forward to the first result (or load it via `fetch` and then swap the `innerHTML`

Downsides: needs three client-side requests (404 page, index, correct page), cannot set the canonical URL when serving the page from a "long URL"

**Comment by davidnuescheler** [comment]
i think that from a practical experience standpoint vanity URLs (or redirects for migration purposes) are combinations (a) of automated transformations of the long URL (let's say strip `/ms/en`) and (b) tables of redirects/vanity URLs which are usually updated manually. for (b) i think that it would be great to provide a `.json` table, which would be editable as a excel (or google) spreadsheet, which is in many cases how these are kept.

i am also hesitant to introduce a dependency on query for request URL resolution, which seems to be categorically more crucial than our current use of query, especially if we assume that we would use (rightfully) the short/vanity URL as the canonical URL for SEO purposes.

**Comment by trieloff** [comment]
## Possible implementation II (`theblog` only, but requires custom code)

- we maintain a Google Spreadsheet with short URLs/long URLs
- we provide a Runtime action or CLI program similar to the importer that will
  - pull the Google Spreadsheet
  - create rewrite rules in the outer CDN config (needs Fastly token)
  - be run periodically or upon spreadsheet update

Upsides: none of the downsides of the solution I: https://github.com/adobe/theblog/issues/133#issuecomment-591893437 very fast and robust, as the rewrites are handled on the CDN level, can be ported to a Helix Proper-level solution quite easily.

So-sos: vanity URLs are managed in one central place instead of each document individually

Downsides: canonical URLs are harder to extract and render in HTML (unless we keep them in the markdown and the spreadsheet), the solution is less portable and requires an outer CDN

**Comment by rofe** [comment]
@trieloff I think this use case could be achieved with #316 for now. Can we close this issue?

**Comment by trieloff** [comment]
We could also set up a second indexer that updates the excel table automatically, so that authors don't have to add entries.
