### ISSUE TITLE
Change URL to theblog.adobe.com

### ISSUE THREAD

**Issue by trieloff** [adobe/theblog#134]
This is one of the critical go-live tasks. 

The [Fastly Service Config](https://manage.fastly.com/configure/services/6v0sHgrPTGUGS5PHOXZ0H1) has been set up to:
- serve traffic from three domains: https://theblog.helix-demo.xzy https://theotherblog.helix-demo.xyz and https://theblog.adobe.com (the last one is not reachable through Fastly, as the DNS has not been updated)
- serve traffic from two backends: Helix Pages and the existing Wordpress site
- with one rule: if the requested hostname is `theotherblog.helix-demo.xyz` or `theblog.adobe.com`, then serve from Wordpress, otherwise serve from Helix Pages

In order to get traffic served from Fastly, we need to:

- [ ] upload the certificate for `theblog.adobe.com` to Fastly (using Fastly Support)
- [ ] update the DNS records for `theblog.adobe.com` to point to Fastly

At this time, the old Wordpress blog will be served from Fastly, and no change should be visible to end users.

In order to get some traffic served from Helix Pages (as a canary), we need to:

- [ ] update the "Request old Blog" condition to exclude certain IP ranges or countries

In order to get all traffic served from Helix Pages (go-live), we need to:

- [ ] update the "Request old Blog" condition to no longer include `|| req.http.Host == "theblog.adobe.com"`

**Comment by rofe** [comment]
@trieloff can you drive this?

**Comment by trieloff** [comment]
Sure, but I don't know who the people holding the DNS config and certs are. Pointers are welcome.

**Comment by rofe** [comment]
I'll send you some contacts via email.

**Comment by trieloff** [comment]
From Perry:

> Keeping the existing Akamai CDN domain functional
> The current Akamai CDN domain (`theblogimages.adobe.com`) is used for image/asset offload for the Wordpress site and it uses the Wordpress site as its origin (`theblog.adobe.com`).  If you are doing DNS magic on `theblog.adobe.com` for a controlled blog rollout, you need to ensure that the Akamai domain is *always* leveraging the Wordpress host as it’s origin.  If you start to split traffic, then you could see the Wordpress site start to break down if the Akamai CDN references start pulling from the new blog site. 

I'll make sure that `/wp-content/` is always served from Wordpress, even after the switchover. This ensures that Akamai will be able to fetch from `theblog.adobe.com` even if it's not Wordpress serving it directly, but Wordpress via Fastly.

**Comment by trieloff** [comment]
Done. You can try 
1. https://theotherblog.helix-demo.xyz/wp-content/uploads/2020/03/desert-portals-night-wichoria-e1584134095822-1800x0-c-default.jpg
2. https://theotherblog.helix-demo.xyz/wp-content/uploads/2020/03/desert-portals-night-wichoria-e1584134095822-1800x0-c-default.jpg

As written above, `theotherblog.helix-demo.xyz` behaves exactly like `theblog.adobe.com` will behave after the Fastly switch, while `theblog.helix-demo.xyz` behaves like the site will behave after turning on Helix. In this case, they both deliver Wordpress images.

**Comment by trieloff** [comment]
Quick update:

- we have a certificate, which has been made available to Fastly
- Fastly is ready to serve traffic at `theblog.adobe.com` once the DNS change has been made

You can try it yourself by adding following line to your `/etc/hosts`

```hosts
151.101.2.122	theblog.adobe.com
```

I've inquired on DL-DDI how to make and how to time the DNS change.

**Comment by trieloff** [comment]
Closing. This task has been made obsolete by #197 and the new plan.
