### ISSUE TITLE
fstab: use drive id instead of sharelink

### ISSUE THREAD

**Issue by tripodsan** [adobe/theblog#135]
the `fstab.yaml` contains a human readable sharelink which reveals too much information.
it would be better to use the internal onedrive id, eg:

```
/drives/b!PpnkewKFAEaDTS6slvlVjh_3ih9lhEZMgYWwps6bPIWZMmLU5xGqS4uES8kIQZbH/root:/theblog
```

**Comment by rofe** [comment]
How can one obtain such a URL?

**Comment by dominique-pfister** [comment]
There's another obstacle: `fstab.yaml` declares the `url` to be of type `uri`, so setting that entry to a value such as the one above will generate a validation error.

**Comment by dominique-pfister** [comment]
> How can one obtain such a URL?

This information is returned by `OneDrive.resolveSharedLink` in `helix-onedrive-support` when passing a `shareLink` such as the one currently used in `fstab.yaml`.

**Comment by trieloff** [comment]
Is there an easy way for a non-technical end user to copy the drive ID from a web interface?

**Comment by tripodsan** [comment]
> There's another obstacle: `fstab.yaml` declares the `url` to be of type `uri`, so setting that entry to a value such as the one above will generate a validation error.

yes, we need to change this...

**Comment by tripodsan** [comment]
> Is there an easy way for a non-technical end user to copy the drive ID from a web interface?

he can use the bulk-editor. https://app.project-helix.io/bulkedit/#/export
just copy-paste the sharelink, click browse, and then select the folder.
after that, the item-path is present in the input box.

eg: '/drives/b!PpnkewKFAEaDTS6slvlVjh_3ih9lhEZMgYWwps6bPIWZMmLU5xGqS4uES8kIQZbH/items/01DJQLOW7RTXZSBSJMZVBJOQPJQBQFED2V'

**Comment by tripodsan** [comment]
(btw: for google, it's just the folder-id... so not even a path)

**Comment by trieloff** [comment]
In terms of user experience, I'd prefer it if we could stick to URIs that are copiable from the Google or Word web UI. If that means an additional step in resolving, so be it, but I feel that copying only a part of a URL, from a different UI might be too error-prone.

**Comment by tripodsan** [comment]
> If that means an additional step in resolving, so be it, but I feel that copying only a part of a URL, from a different UI might be too error-prone.

it's not about resolving time, it about obscuring the potential secrets. for example, revealing the tenant (adobe), sharepoint site (theblog) and root document might not be desired.

What about:
- the helix-bot detects the fstab with the sharelink
- the helix-bot creates a PR with the new drive id, leaving a comment in the yaml.
- the customer can merge the PR, with or without the comment.

**Comment by tripodsan** [comment]
> we could stick to URIs that are copiable from the Google

btw, for google, we can already copy the folder id from the browser url, eg:
https://github.com/davidnuescheler/thinktanked/blob/master/fstab.yaml

**Comment by trieloff** [comment]
I like the bot idea.

**Comment by davidnuescheler** [comment]
i definitely agree with @trieloff that the user experience is best if we support the easy copy of a link from the browser or use the share link. i think for sharepoint/onedrive we could support additionally an id-only based approach that does reveal the additional folder structure.

i am generally totally in support of infrastructure that let's us create PRs from the helix bot, i am not sure that this would be the most pressing starting point though.

**Comment by rofe** [comment]
Closing for now.
