### ISSUE TITLE
Add rewrite logic from imported original URL to Helix Pages URLs

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#136]
While we're still discussing the ideal implementation for vanity URLs (#133), we should at least have a rewriting logic for the original URLs of any imported articles from theblog.adobe.com - which are indexed by search engines and aved in visitor's browser histories etc - to the Helix Pages ones. Once we flip the switch we would let search engines index "our" sitemap.xml and just keep using the Helix Pages URLs.

So maybe a custom 404 handler matching the document name against the list of original URLs? Ideas welcome.

@trieloff @davidnuescheler @kptdobe

**Comment by trieloff** [comment]
If the importer could generate a list of old URL, new URL pairs, then I could script the Fastly API in the outer CDN to redirect old URLs to new URLs.

As long as we are in canary mode, I'd do temporary redirects, so that search engines keep the old URL in their index. After the switchover, we can have permanent redirects.

I wouldn't use the vanity URL feature for this.

**Comment by rofe** [comment]
I think we should already be able to craft the new URL from the data stored by the importer in `/admin/importer/urls.xlsx`.

**Comment by trieloff** [comment]
Is that file committed somewhere?

**Comment by tripodsan** [comment]
> Is that file committed somewhere?

https://adobe.sharepoint.com/:x:/r/sites/TheBlog/_layouts/15/Doc.aspx?sourcedoc=%7B6F377524-EC59-427A-8756-5FB3FD184BF8%7D&file=urls.xlsx&action=default&mobileredirect=true

ideally, it should also contain the document location.... @kptdobe can you add this information?

**Comment by trieloff** [comment]
I've requested access.

**Comment by kptdobe** [comment]
I can add whatever you need. For now, the import is simple, it goes from `/abc` to `/ms/archive/2020/abc`, for all the imported files.

**Comment by trieloff** [comment]
Is it always `2020` or are there different values for the year? If it's always `2020`, that would ease the rule quite a bit.

**Comment by kptdobe** [comment]
Ah sorry, no, it is the year extracted from the `article:published_time` meta tag from the original post entry.
So correct answer should be like `/abc` map to `/ms/archive/<year>/abc`.
The year has its own column in the Excel file but I can store the full path as a new column.
Just tell me what you need.

**Comment by trieloff** [comment]
Ok, I'll get VCLing

**Comment by kptdobe** [comment]
But what extra info do you need in the file ?

**Comment by rofe** [comment]
I'd prefer to keep the assembly of the new URLs in the importer and have the VCL just read them from the `urls.xlsx`.

**Comment by trieloff** [comment]
> But what extra info do you need in the file ?

None. I'll do a lookup of path to year and assemble the correct URL. All the URLs will be loaded into an edge dictionary. You can try this here:  https://theblog.helix-demo.xyz/taylors-universitys-unique-digital-experience-for-every-student/ (only URL currently in the dictionary)

**Comment by kptdobe** [comment]
Ok.
FYI, missing `en`. Real correct answer is: `/abc` maps to `/ms/en/archive/<year>/abc.html`

**Comment by trieloff** [comment]
PR submitted here: https://github.com/kptdobe/helix-theblog-importer/pull/1

Once it's merged I will import the URLs already in the excel spreadsheet.

**Comment by rofe** [comment]
But what if we (or the customer) decided to change the structure (e.g. introduce a month folder)? I would only compute the path in a single location: the importer.

**Comment by kptdobe** [comment]
I think it is better like it is now: if you change the structure (like get rid of `archive`), you only need to change the VCL code.
If you include a month folder, you have to change everything anyway :)

**Comment by rofe** [comment]
> if you change the structure (like get rid of archive), you only need to change the VCL code.

I don't think I understand: wouldn't you have to change the importer as well?

**Comment by kptdobe** [comment]
you right, I forgot a piece ;)

**Comment by trieloff** [comment]
Done. Old posts have been imported using this: https://github.com/trieloff/theblog-redirect-importer new posts are imported through the updated importer.
