### ISSUE TITLE
remove Google Drive mountpoint and move the OneDrive one back to /

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#137]
Now that we have decided on using OneDrive for theblog, we no longer need to distinguish between OneDrive and Google Drive in the path (see #33). So we should dump `/g` and change `/ms` back to `/` (or something generic like `/content`.

- [x] Algolia: exclude `/ms` from `path` and `parents` and `dir` of all entries, or prepare re-indexing everything
- [ ] Fastly: adapt redirect rule to exclude `/ms`

**Comment by rofe** [comment]
@tripodsan is it safe now to switch back to `/`?

**Comment by tripodsan** [comment]
> @tripodsan is it safe now to switch back to `/`?

yes...I don't know about the re-indexing, though....

**Comment by rofe** [comment]
Yes, the index is something we need to coordinate. @dominique-pfister is there a way to do this directly on the index, or do we need full re-indexing?

**Comment by dominique-pfister** [comment]
I haven't seen any command to modify records batch-wise, so we'd either need to do a full re-index, or write some tool that iterates through all index records and patches the paths (and the parents array, too).

**Comment by rofe** [comment]
Whichever is easier 😄 

Could you prepare for one solution and let me know? I'll add a checkbox with pre-requisites to the description above, each of which needs to be ticked off before making the cutover.

**Comment by rofe** [comment]
@trieloff I added one for Fastly ^^

**Comment by rofe** [comment]
https://remove-gdrive--theblog--adobe.project-helix.page/en/archive/2020/february-photography-releases.html
vs
https://theblog-adobe.project-helix.page/ms/en/archive/2020/february-photography-releases.html

Looks ok to me, but I'd be glad if @kptdobe could give it another look...

**Comment by kptdobe** [comment]
Look the same for me. And no error in the network tab.

**Comment by dominique-pfister** [comment]
As a follow-up: the mount (e.g. `/ms`) is also present in the _objectID_ which has the format `branch`-`path`, e.g. `master--ms/de/posts/remove-the-mapping-misery-and-keep-the-creativity.html`. 

If we'd modify a record's objectID, Algolia would **duplicate** that record - one with the old, one with the new objectID - which we probably want to avoid.

If we can guarantee, however, that no future path will ever match `ms/en/posts/...` we can just modify the other fields in every record of the index and keep the "legacy" objectID, otherwise a full re-index is required.

**Comment by rofe** [comment]
Thanks for spotting. I'd say it's highly unlikely that future paths would ever be identical, even if we decided to go back to `/ms` at some point. We will also have year, month and possibly day in the path. 

Therefore I would keep the objectIDs of existing entries as is.

**Comment by rofe** [comment]
Code changes in the branch are tested and approved, @dominique-pfister is working on an update script. We can pull the trigger on both as soon as Algolia lets us in again 😄

**Comment by dominique-pfister** [comment]
Script available: https://github.com/dominique-pfister/changemount

**Comment by rofe** [comment]
@trieloff could you adjust the Fastly redirect logic so legacy paths will work as well?
