### ISSUE TITLE
[Post] Product banner not rendered correctly

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#138]
Comparing https://theblog.adobe.com/share-like-a-boss/ with https://theblog.helix-demo.xyz/ms/en/archive/2020/share-like-a-boss.html there's some sort of product or campaign banner at the bottom of the page which gets rendered as normal text instead of a banner.

@davidnuescheler @kptdobe

**Comment by rofe** [comment]
Another example appeared today: 
- theirs: https://theblog.adobe.com/xd-march-2020-audio-prototyping-anchor-links-more/
- ours: https://theblog-adobe.hlx.page/ms/en/archive/2020/from-fries-to-phones-leviathan-uses-adobe-xd-to-design-interactive-experiences.html

**Comment by kptdobe** [comment]
This is not really a bug but a "not-implemented".

The current implementation of the design (and consequently the importer) covers only the simple design / component cases. There is a variety of "components" from the original system we do not cover yet. To do so, we should create a list of all possible "components" authors can inject in the post, decide if this will be supported and if yes, find a corresponding mapping in MD. This list can only come from someone knowing the original system and the authors needs.

Another example: https://theblog.adobe.com/what-you-missed-from-sneaks-at-max-2018/ (MAX 2018 "featured" collection).

**Comment by rofe** [comment]
bug or missing feature - I really think we should look into how we can support these banner type components. just found another example ("covid-19 response"):
- theirs: https://theblog.adobe.com/4-ways-media-and-entertainment-companies-can-navigate-covid-19/
- ours: https://theblog.helix-demo.xyz/en/archive/2020/4-ways-media-and-entertainment-companies-can-navigate-covid-19.html

**Comment by rofe** [comment]
Requires #162

**Comment by rofe** [comment]
Handled in https://github.com/adobe/helix-theblog-importer/issues/12

**Comment by kptdobe** [comment]
I disagree that this is fully handled in adobe/helix-theblog-importer#12. The role of the importer is to make sure the old content is transformed into the newly defined content structure in the markdown. But something still needs to render it properly, i.e. some css classes must certainly display it. This is the goal of this ticket.

**Comment by rofe** [comment]
Well, I thought this was the role of #162  🙂
