### ISSUE TITLE
Post without hero image

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#140]
It occasionally happens that imported posts don't have a hero image even though the original post had one.
- Latest example: https://theblog.helix-demo.xyz/ms/en/archive/2020/adobe-withdraws-from-nab-show-2020.html
- Original: https://theblog.adobe.com/adobe-withdraws-from-nab-show-2020/

**Comment by kptdobe** [comment]
For that specific case, I suspect the image was missing in the original post... Post has a modified date 1h after the publish date which means it has been modified quickly after initial publish. I re-imported the file and it worked with no code change.

**Comment by kptdobe** [comment]
The "modified" use case is not covered and is something we might need to think of if this is occurring often.

**Comment by rofe** [comment]
We should also think about making the display part more resilient and not show a broken image if there is no hero image...
