### ISSUE TITLE
Hero image not showing up on some articles

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#149]
The hero image on https://theblog.helix-demo.xyz/ms/en/archive/2020/10-must-haves-for-your-data-toolkit.html is broken. The output is
```xml
<?xml version="1.0" encoding="utf-8"?>
<Error>
  <Code>BlobNotFound</Code>
  <Message>
    The specified blob does not exist. RequestId:a35c2727-901e-000b-0e69-04e9db000000 Time:2020-03-27T18:54:36.4578775Z
  </Message>
</Error>
```

(Original image: https://theblogimages.adobe.com/wp-content/uploads/2020/03/2020.03_10MustHavesInYourDataToolset_Bloghero_1600x700.jpeg)

@kptdobe @tripodsan

**Comment by rofe** [comment]
https://theblog.helix-demo.xyz/ms/en/archive/2020/your-tutorial-resource-guide-to-digital-art-design.html is another one, same error.

**Comment by kptdobe** [comment]
Humm... at the moment, theblog.adobe.com seems to have serious issues... In a browser and on various blog post entries, I get:

```
This page isn’t workingtheblog.adobe.com didn’t send any data.
ERR_EMPTY_RESPONSE
```

Digital Summit effect ?

**Comment by kptdobe** [comment]
I re-run the import and purged the corresponding blog posts and images urls. Fixed.
