### ISSUE TITLE
Influence order of posts on homepage and topic pages

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#155]
We need articles to publish by default in chronological order, as we have now, but we also need to be able to move articles around on both the homepage and category pages. So if an important news item needs to keep top billing for a few days, we can make that happen.

**Comment by rofe** [comment]
@davidnuescheler suggested that we enable this by allowing the curator to add a list of links to the homepage or topic page using Word. Links can simply be absolute URLs copied from the staging environment. Helix would clean them up automatically to hide backend specifics. On the blog side, we would detach the list from the DOM and reorder the query hits accordingly.

**Comment by davidnuescheler** [comment]
i quickly prototyped an implementation... find here:
https://featured-posts--theblog--adobe.hlx.page/

**Comment by rofe** [comment]
Cool! 

Should we make the featured posts an ordered list? I think it would be more explicit for the curator, and we could simply look for a `<ol>` in the DOM, wherever it is...

I'd propose to open a PR for easier collaboration.

**Comment by davidnuescheler** [comment]
i was thinking that initially as well, and then i realized that depending on how this goes, it may or may not be easier.... currently i am looking for a section that has a title "featured posts" and then simply take all the links in there... i don't think the additional constraint of an `<ol>` is really helpful, but you should be able to use a list as a best practice in the `index.docx` already... 

btw. this should almost already work on topic and possibly author pages as well... just in case someone wants to try that...

**Comment by rofe** [comment]
>  i don't think the additional constraint of an `<ol>` is really helpful

It might be quicker for users to just insert a list than to type "featured posts" 😉. Also, we wouldn't force non-English speakers to write English in a different language branch...

> but you should be able to use a list as a best practice 

Makes sense.

I successfully used it on the German homepage: https://featured-posts--theblog--adobe.hlx.page/de

**Comment by rofe** [comment]
Tested on homepage, topic and author page.

**Comment by rofe** [comment]
# Documentation
## Homepages
1. Open the top level `index.docx` for the global homepage, or the one in a language folder
1. Add a section underneath the title by typing --- (three dashes) followed by a line break
1. Type **Featured Posts** and give it the style _Heading 2_
1. Below, insert an set of links to blog posts in the order you want them to appear
1. Refresh the homepage in your browser

## Topic or author pages
1. Navigate to the `.md` file of the author or topic you want to add featured posts to, then click _Open in Text Editor_.
1. Add a section underneath the title by typing --- (three dashes) followed by a line break
1. Type `## Featured Posts
1. Below, insert an set of links to blog posts in the order you want them to appear
1. Refresh the topic or author page in your browser
