### ISSUE TITLE
Implement new folder structure in client side code

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#164]
New structure:
- theblog
  - en
    - drafts
      - migrated
        - yyyy
          - mm
            - dd
      - localized
    - publish
      - yyyy
        - mm
          - dd
    - send-to-localization
    - topics
    - authors
    - products
    - promotions
  - assets
    - products
    - promotions

**Comment by rofe** [comment]
Beware: on the client side, `publish` may or may not be part of the URL, see #169.

**Comment by rofe** [comment]
@dominique-pfister we will need to make some changes to the indexing listeners:
- `en/posts` has been renamed to `en/publish` - same purpose, not sure if that changes anything regarding indexing listener
- `en/archive` has been removed and
- `en/drafts/migrated` introduced: the idea is that we import to `en/drafts/migrated` from now on, so the content team and we can spot check individual articles, fix any bugs and implement missing features (like #162) before doing a final import directly to `en/publish` before go-live. I think for the time being, we need to add an indexing listener on `en/drafts/migrated` s well, so the imported content will still show up on the homepage. @kptdobe wdyt?

**Comment by rofe** [comment]
I think that once https://github.com/adobe/helix-theblog-importer/issues/10 will be ready, we should disable the indexing listener on `en/archive`, delete that folder, and all current items in the index. Then add an indexing listener to `en/drafts/migrated` before running the import to the new structure. This will refill the index with the new paths.

(Note: we can't just patch the existing items in the index, because the new path structure will also include the days)

**Comment by tripodsan** [comment]
I don't think this is a good hierarchy, I think it would be better if the language directories are below each of the _special_ directories: `publish/en`, `drafts/en`, `authors/en`, etc..

because:
- to add a new language, you need to create all the new _special_ directories
- changing the structure later is easier, if it's toplevel
- it is more natural to mount `/publish` below the exported root, than to rewrites the path to `/{lang}/publish/...`.
- adding localized assets will be simpler

**Comment by tripodsan** [comment]
> because we also want to be able to deliver articles from drafts, and other content from authors, topics, products and promotions.

hmm.. ok.

**Comment by tripodsan** [comment]
> because we also want to be able to deliver articles from drafts, and other content from authors, topics, products and promotions.

hmm.. ok.

**Comment by rofe** [comment]
IA change complete. Here's the protocol (might be useful for another time):

1. prepare necessary code changes in a branch 
1. disable notifications on New Relic monitor for the uncached site
1. disable indexing 
1. make necessary file/folder changes in OneDrive
1. enable indexing again
  _wait for indexing to complete_
1. merge code branch
1. check site manually
  _wait appr. 15 minutes for New Relic monitor to turn green again, too_
1. enable notifications on New Relic monitor again
