### ISSUE TITLE
GetSocial integration

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#165]
- GetSocial (vendor/tool) is the tool currently used for Social Sharing
- Social Sharing feature is added to Article Pages (part of template designs)
- GetSocial provides JS to be included on the page (article pages)

@avanishgandhi to provide more details.

**Comment by avanishgandhi** [comment]
I will setup a call with the resource from GetSocial to start the integration discussion.

**Comment by rofe** [comment]
Test URL: https://getsocial--theblog--adobe.hlx.page/en/drafts/migrated/2020/03/04/kayo-sports-scores-big-with-new-subscriptions.html

The experience can be customized on getsocial.io (login provided in private).
