### ISSUE TITLE
Multimedia Support

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#166]
- Support for Videos (youtube or AEM hosted)
- Support for Slide Share
- Support for Podcasts

@avanishgandhi to provide an existing example for each media type.

**Comment by avanishgandhi** [comment]
ok, i will hunt examples today and get back to you as soon as i get them

**Comment by rofe** [comment]
Yes, ideally examples of different media types used in theblog articles today.

**Comment by avanishgandhi** [comment]
@rofe - below are the three sample provided to show samples.

Video: https://cmo.adobe.com/articles/2019/11/editor-s-picks--the-funniest-ads-of-all-time.html
 
Podcast: https://cmo.adobe.com/articles/2019/8/podcast-how-to-organize-for-success-in-travel--hospitality.html
 
Slideshare: https://cmo.adobe.com/articles/2020/1/adobe--2019-online-holiday-shopping-growth-driven-primarily-by-s.html

**Comment by rofe** [comment]
@avanishgandhi thanks! Do you you also have an example of an "AEM hosted" video as mentioned in the description above?

**Comment by rofe** [comment]
Youtube Test: 
- Content: https://adobe.sharepoint.com/sites/TheBlog/_layouts/15/doc.aspx?sourcedoc={827faa9b-cddf-4c64-91e1-108d584b0683}&action=edit
- Preview: https://theblog-adobe.hlx.page/en/drafts/youtube-test.html

**Comment by trieloff** [comment]
Slideshare works in `helix-embed`: https://adobeioruntime.net/api/v1/web/helix/helix-services/embed@v1/https://www.slideshare.net/adobe/adobe-digital-insights-holiday-recap-2019?ref=https://cmo.adobe.com/

But we need to whitelist the URL pattern in `helix-pipeline`

**Comment by rofe** [comment]
YouTube, SlideShare and SoundCloud are all working now:
https://theblog-adobe.hlx.page/en/drafts/embed-test.html

**Comment by trieloff** [comment]
@rofe could we set up a persistent browser based test for the embeds? They can break if:
- any of the sites change their markup
- iframely has a bug
- helix-embed has a bug
- helix-pipeline has a bug
- word2md has a bug
- an angry god just wants to see us suffer

**Comment by avanishgandhi** [comment]
@rofe I added AEM videos as i currently see videos on CMO Skyline instance of AEM. I asked Biz team and they could not recollect if they have used any of the videos from AEM. I am asking others to see if these video are ever referenced in articles

![image](https://user-images.githubusercontent.com/62259400/80500279-da256a80-8922-11ea-9c69-c48944c75d54.png)

**Comment by avanishgandhi** [comment]
Can we also do Demo of User stories we complete? That we way we can show Biz team of the progress we are making.
thanks
Avanish

**Comment by rofe** [comment]
> I am asking others to see if these video are ever referenced in articles

I remember there being a reference search in AEM Assets.

**Comment by rofe** [comment]
> could we set up a persistent browser based test for the embeds?

If you give me a test page with examples of all supported embed types, I can set up the monitor script and automation in `helix-embed`.
