### ISSUE TITLE
SEO & Other Metadata

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#167]
- Ability to add and mange keywords Metadata to be added to the article and category pages
- Ability to add and mange Description Metadata to be added to the article and category pages
- Add SERP_Content_Type and Primary Product Metadata to articles to support custom Adobe Search categorization.
- Support Canonical metadata
- Support Href-Lang metadata
- Support 3rd party metadata to templates; example
  - OpenGraph
  - Twitter
  - Google Site verification

**Comment by rofe** [comment]
A pragmatic approach would be to try to inject the SEO related meta tags and links on the client side. Based on what we see in articles on theblog.adobe.com, it would  essentially be the following:
```html
 <meta name="description" content="We’re proud to be partnering with iconic artists and creative luminaries from around the world to honor the workers and volunteers who are making a difference during th..."/>
 <link rel="canonical" href="https://theblog.adobe.com/using-creativity-to-honorheroes-doing-extraordinary-things-during-covid-19/" />
 <link rel="publisher" href="https://plus.google.com/+Adobe"/>
 <meta property="og:locale" content="en_US" />
 <meta property="og:type" content="article" />
 <meta property="og:title" content="Using Creativity to #HonorHeroes Doing Extraordinary Things During COVID-19 \| Adobe Blog" />
 <meta property="og:description" content="We’re proud to be partnering with iconic artists and creative luminaries from around the world to honor the workers and volunteers who are making a difference during th..." />
 <meta property="og:url" content="https://theblog.adobe.com/using-creativity-to-honorheroes-doing-extraordinary-things-during-covid-19/" />
 <meta property="og:site_name" content="Adobe Blog" />
 <meta property="article:publisher" content="https://www.facebook.com/Adobe" />
 <meta property="article:tag" content="COVID-19" />
 <meta property="article:tag" content="Direct Relief" />
 <meta property="article:tag" content="Honor Heroes" />
 <meta property="article:tag" content="Shepard Fairey" />
 <meta property="article:section" content="Creativity" />
 <meta property="article:published_time" content="2020-04-14T16:05:55+00:00" />
 <meta property="article:modified_time" content="2020-04-15T19:33:48+00:00" />
 <meta property="og:updated_time" content="2020-04-15T19:33:48+00:00" />
 <meta property="og:image" content="https://theblogimages.adobe.com/wp-content/uploads/2020/04/Unknown.jpg" />
 <meta property="og:image:secure_url" content="https://theblogimages.adobe.com/wp-content/uploads/2020/04/Unknown.jpg" />
 <meta property="og:image:width" content="1600" />
 <meta property="og:image:height" content="700" />
 <meta property="og:image:alt" content="Image of medical professional." />
 <meta name="twitter:card" content="summary_large_image" />
 <meta name="twitter:description" content="We’re proud to be partnering with iconic artists and creative luminaries from around the world to honor the workers and volunteers who are making a difference during th..." />
 <meta name="twitter:title" content="Using Creativity to #HonorHeroes Doing Extraordinary Things During COVID-19 \| Adobe Blog" />
 <meta name="twitter:site" content="@Adobe" />
 <meta name="twitter:image" content="https://theblogimages.adobe.com/wp-content/uploads/2020/04/Unknown.jpg" />
 <meta name="twitter:creator" content="@Adobe" />
```
I think we have most of the dynamic values to fill in (i.e. title, description, image URL, tags, dates) or can hardcode them (i.e. Adobe social media handles). And for the ones we don't have (modified time, updated time) - I'm wondering if we need those at all.

**Comment by trieloff** [comment]
@ramboz do you think this would be possible with `helix-markup.yaml`?

**Comment by trieloff** [comment]
These could be dynamic, as we expect search engines to execute our JS

```html
 <meta name="description" content="We’re proud to be partnering with iconic artists and creative luminaries from around the world to honor the workers and volunteers who are making a difference during th..."/>
 <link rel="canonical" href="https://theblog.adobe.com/using-creativity-to-honorheroes-doing-extraordinary-things-during-covid-19/" />
```

These can be in the static HTML because they are the same for every page

```html
 <link rel="publisher" href="https://plus.google.com/+Adobe"/>
 <meta property="og:locale" content="en_US" />
 <meta property="og:type" content="article" />
 <meta property="og:site_name" content="Adobe Blog" />
 <meta property="article:publisher" content="https://www.facebook.com/Adobe" />
 <meta name="twitter:site" content="@Adobe" />
 <meta name="twitter:creator" content="@Adobe" />
```

For the remaining Twitter and OG tags, we would need to find a server-side solution, as the Twitter and Facebook don't execute JS for expanding snippets.

**Comment by rofe** [comment]
Relevant documentation from Google: https://developers.google.com/search/docs/guides/javascript-seo-basics

**Comment by rofe** [comment]
Test URL: https://metadata--theblog--adobe.hlx.page/en/drafts/migrated/2020/03/04/kayo-sports-scores-big-with-new-subscriptions.html

**Comment by rofe** [comment]
I agree with @trieloff that sharing (which seems to be the main usecase for these tags) will not work if meta tags are added on the client side. Created https://github.com/adobe/helix-pages/issues/261 instead.

**Comment by rofe** [comment]
In summary, metadata will be added to articles in 3 different ways:
- `og:*` tags (title, description, image) will be added server side by the platform (Helix Pages)
- static (same for all articles) `article:*` and `twitter:*` tags (publisher, site_name, creator) will be added server side by the project code
- dynamic `article:*` tags (published_time, section, tags) will be added client side by the project code (Google will be able to handle this)

**Comment by rofe** [comment]
Twitter requires some more work, see https://github.com/adobe/helix-pages/issues/272

**Comment by rofe** [comment]
Test sharing renditions with:
- [ ] Facebook
- [ ] Twitter
- [ ] LinkedIn
- [ ] WhatsApp
- [ ] iMessage

**Comment by trieloff** [comment]
- [ ] Slack?

**Comment by rofe** [comment]
Test how search engines interpret the metadata:
- [ ] Google

**Comment by davidnuescheler** [comment]
on the google site verification... i think that should rather be in its own `.html` verification file provided by google instead of cluttering up the meta data of every page.

**Comment by rofe** [comment]
I fully agree. I don't know the owner of the verification key in the metadata, I only copied it over so whoever managed the legacy site in the Google Search Console could also add the Helix site. I thought this might come in handy for direct comparison at some point.

For now I also committed my own verification file. I'll happily invite more folks to that.

**Comment by rofe** [comment]
@avanishgandhi I'm about to close this out for now. On your original requirements:
> Ability to add and mange keywords Metadata to be added to the article and category pages

Authors can add topics and products to the bottom of the Word document, either manually or using the [Tagger](https://app.project-helix.io/bulkedit/#/tagger) tool. Both will be added as metadata.

> Ability to add and mange Description Metadata to be added to the article and category pages

The description will be generated from the first text paragraph (truncated to 25 words) and added as metadata.

> Add SERP_Content_Type and Primary Product Metadata to articles to support custom Adobe Search categorization.

Need more info. But it sounds like something we should probably handle in a dedicated issue.

> Support Canonical metadata
> Support Href-Lang metadata
> Support 3rd party metadata to templates; example
> OpenGraph
> Twitter
> Google Site verification

All of these are now added as metadata.

You can check e.g. https://theblog.helix-demo.xyz/en/drafts/migrated/2020/03/04/kayo-sports-scores-big-with-new-subscriptions.html (both source code and rendered DOM)
