### ISSUE TITLE
Implement 301 redirect strategy

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#168]
@agandhi to provide more details on redirect strategy.

**Comment by kptdobe** [comment]
I think this is related to https://github.com/adobe/helix-shared/issues/282

**Comment by trieloff** [comment]
I don't think we need adobe/helix-shared#282 for that, just a list of from-to-pairs or patterns is enough and we can hardcode it in Fastly.

**Comment by rofe** [comment]
@avanishgandhi what's the status here?

**Comment by davidnuescheler** [comment]
this seems to be working... can we close this issue?

see: https://blog.adobe.com/listening-learning-and-taking-action/

**Comment by rofe** [comment]
@avanishgandhi stated [here](https://github.com/adobe/theblog/issues/198#issuecomment-628087691) that this issue is complementary to https://github.com/adobe/theblog/issues/198 where we implemented the old to new post URL mapping, but we are still waiting for more details. Removing batch-1 label for now.

**Comment by rofe** [comment]
@avanishgandhi can we close this one now?
