### ISSUE TITLE
Implement URL mapping

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#169]
Published articles live under `publish/yyyy/mm/dd/foo.docx`. `publish` should be hidden from the URL:
`http://theblog.helix-demo.xyz/en/yyyy/mm/dd/foo.html`
should connect to
`http://theblog-adobe.hlx.page/en/publish/yyyy/mm/dd/foo.html`
in the backend.

**Comment by rofe** [comment]
@trieloff could you take this?

**Comment by avanishgandhi** [comment]
I add this ask in the PRD requirements too - 

New Blogs will support the following URL structure
URLs for live blogs will be www.newblogdomaingoeshere.com/en/2020/04/22/article-name-goes-here.html

**Comment by avanishgandhi** [comment]
i think the only part missing from the GIT issue above is the language of the article

**Comment by rofe** [comment]
Adeed the language, nice catch @avanishgandhi!

**Comment by trieloff** [comment]
So the rewrite rule would be:

from: `/en/(\d\d\d\d/\d\d/\d\d)/(.*).html`
to `/en/$1/$2.html`

correct?

**Comment by trieloff** [comment]
@rofe do you have an example post that I can use for testing?

**Comment by rofe** [comment]
> correct?

Not quite 😉  it's
from: `/en/(\d\d\d\d/\d\d/\d\d)/(.*).html`
to `/en/publish/$1/$2.html`

But note that `en` could be any language, so maybe:

from: `/(.*)/(\d{4}/\d{2}/\d{2})/(.*).html`
to `/$1/publish/$2/$3.html`

**Comment by rofe** [comment]
> do you have an example post that I can use for testing?

https://new-ia--theblog--adobe.hlx.page/en/publish/2020/04/30/AG-Test.html

**Comment by rofe** [comment]
@avanishgandhi should we also disallow serving URLs including `/publish/` on the outer CDN altogether?

**Comment by rofe** [comment]
@dominique-pfister the indexer should probably also be adjusted to not store the `publish` path segment in the `path` and `parents`.

**Comment by trieloff** [comment]
https://theblog.helix-demo.xyz/en/2020/04/30/AG-Test.html works now.

**Comment by tripodsan** [comment]
wouldn't it be easier if you put the `publish` above the languages?

**Comment by rofe** [comment]
@tripodsan let's keep this discussion in #164

**Comment by dominique-pfister** [comment]
> dominique-pfister the indexer should probably also be adjusted to not store the `publish` path segment in the `path` and `parents`.

Hm, so for a document `/en/publish/2020/04/30/AG-Test.html`, the indexer should store `en/2020/04/30/AG-Test.html` as path, and `[ '/', '/en', '/en/2020', '/en/2020/04', ... ]` as parents?

**Comment by rofe** [comment]
@trieloff if we index articles without the `publish` segment, we will need the same rewriting logic on the inner CDN as well.

**Comment by trieloff** [comment]
I wouldn't do that. The inner CDN is Shared for all Helix Pages Users.

**Comment by rofe** [comment]
But do we want to keep 2 separate indices?

**Comment by trieloff** [comment]
You could change the base URL for the indexer to use the outer CDN, this way you always see the published paths.

**Comment by rofe** [comment]
Yes, but we store relative paths in the index, meaning links to articles on the homepage would be inherently broken on the inner CDN. And switching to full URLs poiting to the outer CDNs would mean you could no longer "surf" the site from the inner CDN homepage, which would be both confusing and impratical (e.g. when testing branch functionality).

**Comment by tripodsan** [comment]
I would store the true path in the index, and remove the `/publish/` clientside when rendering the links.

**Comment by rofe** [comment]
And how can we reliably know on the client side whether we're on the outer (remove `/publish/`) or inner (keep `/publish/`) CDN? Short of testing the hostname for `.hlx.page`...

**Comment by trieloff** [comment]
What's so bad about checking the hostname?

**Comment by rofe** [comment]
I just think it's ugly... possibly the ugliest compromise we had to make so far 😉

**Comment by trieloff** [comment]
Pretty URLs require ugly compromises.

**Comment by avanishgandhi** [comment]
that should go on a t-shirt

**Comment by rofe** [comment]
What about the `sitemap.xml`? I assume search engines should only index URLs without `/publish/`, so the sitemap should strip them away, too...

**Comment by dominique-pfister** [comment]
As discussed with @rofe, we could create a sitemap configuration that allows changing the path returned. Such a configuration would also come handy later if we decide to *hide* some paths from the sitemap.

Just thought about another approach: we could add support for _computed_ properties in `helix-query.yaml`, e.g.:
```
properties:
  external-url:
    value: |
      replace(path, '/publish/', '/')
```
Sitemap would then use `external-url` and fallback to `path`, WDYT?

**Comment by rofe** [comment]
I like this idea! I would only change the (to-be-well-known) property name from `external-url` to `external-path` in order to avoid confusion, because protocol and host name will still be prefixed by the sitemap.js.

**Comment by dominique-pfister** [comment]
Good point, changed the property name.

**Comment by dominique-pfister** [comment]
Created in issue in helix-shared to change the schema: https://github.com/adobe/helix-shared/issues/291

**Comment by rofe** [comment]
https://theblog-adobe.hlx.page/sitemap.xml is currently empty

**Comment by rofe** [comment]
Ah, silly me: I know why. Closing again.
