### ISSUE TITLE
[Homepage] Create homepage

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#17]
The homepage https://theblog.adobe.com/ has a different layout than the blog entries, we need to:

- [x] style it accordingly
- [x] set the default content
- [x] implement the "latest stories"
- [ ] implement the "popular stories"

**Comment by rofe** [comment]
Requires #23

**Comment by rofe** [comment]
The current state can be observed here:
- http://localhost:3000/index.html
- https://theblog.helix-demo.xyz/index.html

@davidnuescheler it could use some CSS love :) and I'm not sure how we would currently implement the "popular stories" part... maybe we just skip that for the demo...

**Comment by trieloff** [comment]
@rofe I think we can get a JSON file of the popular stories with help from @Marquise Rosier - we may have to add a owner/repo filter to https://github.com/adobe/helix-run-query/blob/master/src/queries/top-pages.sql – but it should be doable.

**Comment by rofe** [comment]
@trieloff cool! @marquiserosier would you like to take a stab at this?

**Comment by MarquiseRosier** [comment]
@rofe sure thing! :) @trieloff since the tables are named according to the serviceid we should be able to query theblog itself

**Comment by MarquiseRosier** [comment]
@rofe @trieloff 
Is this what you guys were looking for? 

https://github.com/adobe/helix-run-query/pull/95

**Comment by rofe** [comment]
@MarquiseRosier cool, thanks! @trieloff can you add it to the homepage?

**Comment by trieloff** [comment]
@MarquiseRosier can you provide the example URL? We can then add it to the homepage and inject the contents.

**Comment by MarquiseRosier** [comment]
Example URL as in branch deployment?

**Comment by trieloff** [comment]
No, it should be merged already.

**Comment by MarquiseRosier** [comment]
Ahh ok? You can verify the action using 
https://adobeioruntime.net/api/v1/web/helix/helix-services-private/run-query@2.2.0/top-blogposts 
I'll update this in the documents. You just have to provide service, token!

**Comment by trieloff** [comment]
I'm removing the auth requirement, let's see how this works.

**Comment by trieloff** [comment]
Nice: `https://adobeioruntime.net/api/v1/web/helix/helix-services/run-query@v2/top-blogposts?limit=10` @kptdobe maybe you can work with this. We don't have any of the metadata that's in the Algolia index, so we will have to find a way to gather it in the front end.

**Comment by MarquiseRosier** [comment]
OK perfect! I'm glad it works :D 
if you need any more help, let me know!

**Comment by MarquiseRosier** [comment]
@trieloff if needed I'd be glad to give absolute URL as the results. This might ensure there's less work on part of the service consumer!

**Comment by rofe** [comment]
Note that we prefixed the URLs with `/ms` recently to be able to showcase Google Drive integration (#33) as well...

**Comment by trieloff** [comment]
Yes, it will take a while for the stats to get updated, but in a month from now, all should be good.

**Comment by rofe** [comment]
Not doing popular stories for the moment. Closing.
