### ISSUE TITLE
Implement localization workflow

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#171]
1. Sign into OneDrive and navigates to the `en/drafts` folder
1. Open the English document to be translated, e.g. `my-article,docx` and add the languages below topics and/or products, for example `Languages: en, fr` for English and French
1. Copy the document to the `en/send-to-localization` folder to initiate the translations:
   1. The language list is extracted, and translation workflows in GlaaS are started for all languages but the original one, using an auto-generated `.md` version of the source file.
   1. The translated version of the `.md` file is automatically copied to  the`fr/drafts/localized` folder
1. Get notified of the new translation by email with both a link to review the article rendered by Helix (e.g. `https://theblog-adobe.hlx.page/fr/drafts/localized/mon-article.html`) and a link to the French `.md` file in OneDrive: `fr/drafts/localized/mon-article.md`.
1. Move the reviewed `.md` file from the `fr/drafts/localized` to the `fr/posts` folder
1. Open https://theblog.helix-demo.xyz/
1. Switch region to France
1. See the new article at the top

**Comment by avanishgandhi** [comment]
Hey @rofe - couple of quick questions.
"Step 3. Copy the file to en/send-to-localization folder" - once the translation is completed what do you with the word file in the en/send-to-localization folder? Will it get auto deleted once the job is complete?

**Comment by rofe** [comment]
> Will it get auto deleted once the job is complete?

I'd say yes. Or even when the translation jobs are started.

**Comment by rofe** [comment]
@avanishgandhi this is probably something for batch-3 (regional blog migration).
