### ISSUE TITLE
Implement new design

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#179]
- [x] Homepage
- [x] Post page
- [x] Category Page
- [x] Author Page

**Comment by rofe** [comment]
@avanishgandhi please add the link to the final approved XD file when available.

**Comment by avanishgandhi** [comment]
The designs will be finalized/approved by Friday as per Matt Rozen. 
Please review the link which shows R3 of the designs 
https://xd.adobe.com/view/288b6892-b75e-465d-62ad-e9b1ed85f7f7-5eba/

**Comment by avanishgandhi** [comment]
we might have some tweaks on the filter UX which we will try and finalize before friday.

**Comment by davidnuescheler** [comment]
adding a couple of URLs for testing new design on existing posts on design branch:

https://design--theblog--adobe.hlx.page/en/drafts/migrated/2020/03/04/kayo-sports-scores-big-with-new-subscriptions.html

https://design--theblog--adobe.hlx.page/en/drafts/migrated/2020/04/01/get-to-great-faster.html

https://design--theblog--adobe.hlx.page/en/drafts/migrated/2020/04/27/the-state-of-utah-uses-adobe-sign-to-accelerate-telework-during-crisis.html

https://design--theblog--adobe.hlx.page/en/drafts/migrated/2020/04/27/throwback-adobe-max-2019-edition.html

https://design--theblog--adobe.hlx.page/en/drafts/migrated/2020/04/30/helping-banks-and-insurance-companies-adapt-in-challenging-times-with-adobe-document-cloud.html

https://design--theblog--adobe.hlx.page/en/drafts/migrated/2020/04/30/coming-together-advocating-for-inclusion-in-the-covid-19-era.html

https://design--theblog--adobe.hlx.page/en/drafts/migrated/2020/03/27/10-must-haves-for-your-data-toolkit.html

https://design--theblog--adobe.hlx.page/en/drafts/migrated/2020/03/27/foundation-for-success.html

**Comment by rofe** [comment]
@avanishgandhi: can we adjust the mobile design so we can use GetSocial out of the box? Instead of showing an inline share bar at the top and bottom of the article body, let’s use a single floating one, either at the bottom (current implementation) or top:
![12855F3E-8AB5-4B7F-8DD8-0B0317CC5D25](https://user-images.githubusercontent.com/1609742/80951468-3e02d400-8df8-11ea-8c4c-1585c036327f.jpeg)
Open one of the links above on a mobile browser to test it out.

**Comment by auniverseaway** [comment]
@rgclayton is going to start doing some CSS work to get the site looking like the new mocks. @rofe do you think it would be a good idea to have a quick sync with maybe you, @avanishgandhi, @rgclayton, and myself?

**Comment by rofe** [comment]
@davidnuescheler already got started on the post/article page, and I was planning on tackling the homepage next. So maybe @rgclayton could start on the topic page or author page? 

Remember, mobile first: mobile is the default, tablet and desktop are the exceptions (with media queries).

**Comment by rofe** [comment]
Final design (from #190 by @avanishgandhi): https://xd.adobe.com/view/b11a5151-ca60-4c4a-4420-967d97346b2e-c72b/grid

**Comment by rofe** [comment]
@rgclayton it would be great if you could tackle the styling for #193.

**Comment by rgclayton** [comment]
@rofe Ok. Taking a look.

cc: @auniverseaway
