### ISSUE TITLE
[Posts] Add Recommended Articles on blog entries

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#18]
Each blog entry has a "Recommended Articles" section at the end, this should be implemented. We need to research if a search can be implemented to do find something meaningful. Otherwise, I do not see how we could implement this in a user friendly matter (no one wants to maintain a list manually for each blog entry).

**Comment by rofe** [comment]
Requires #23

**Comment by rofe** [comment]
If the recommended articles are mostly picked by the author of the article, one way to implement this would be analoguous to how we implemented featured posts (see #155): the author can add a section at the bottom with a list of links, which we would then feed into a query. Something like this:

1. Open an article `.docx` 
1. Add a section underneath the products and topics by typing --- (three dashes) followed by a line break
1. Type **Recommended Posts** and give it the style _Heading 2_
1. Below, insert a set of URLs to existing articles in the order you want them to appear, separated by line breaks
1. Open the article page in your browser and scrioll down to see a wall of recommended article cards.

@davidnuescheler

**Comment by trieloff** [comment]
I would just search for articles with similar topics or authors and show them below.

**Comment by rofe** [comment]
> I would just search for articles with similar topics or authors and show them below.

The desired logic from the customer perspective is still undefined. While we are waiting, I think we should go ahead with the curated approach described above.
