### ISSUE TITLE
Target Markdown specs for migration

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#181]
@rofe I am adding this story to track the documentation/specs of markdown thats support for blog articles to be migrated into. 

- We want to engage Oproma next week and these specs would help get them started at looking at how current Blogs and CMO content markup can be migrated into an appropriate markdown. 

- we understand that the once the designs are finalized, there might be some new markdown specs that might be added to support features such as "recommended for you", tagging and such.

**Comment by rofe** [comment]
Dependencies:
- #162 
- #18

**Comment by rofe** [comment]
Document structure:
```md
---

Title (Heading 1)
Optional subtitle

---

Hero Banner (optional inline image)
Optional caption

---

By John Doe
Published on 11-05-2020

---
Article text
(optional inline image)
Article text
...
---

Topics: Topic1, Topic2 (optional; first topic will be primary)
Products: Product1, Product2

```
`---` designates what we call "sections" in Helix Pages.

**Comment by rofe** [comment]
Multimedia content and promotional banners can be embedded in the article text simply as links:

YouTube video, SlideShare deck, SoundCloud audio etc:
```
![](https://www.youtube.com/watch?v=uxehWEB9Hw8)
```

Promotional banner:
```
![](/en/promotions/covid-19-response.html)

```

**Comment by rofe** [comment]
Documentation of markdown features in Helix:
https://github.com/adobe/helix-pipeline/blob/master/docs/markdown.md
