### ISSUE TITLE
Validate banners with new design

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#188]
A first implementation of banners design has been made with https://github.com/adobe/theblog/issues/162. It has some flaws that we need to be address but after the new design is implemented (see #179).

Here is a list of posts containing different banners to validate:

- https://theblog-adobe.hlx.page/en/drafts/migrated/2020/05/05/stronger-together-supporting-indias-communities-amidst-covid-19.html
- https://theblog-adobe.hlx.page/en/drafts/migrated/2018/07/26/forward-thinking-brands-re-engineer-hiring-for-the-future.html
- https://theblog-adobe.hlx.page/en/drafts/migrated/2018/02/15/creative-refresher-capture-transforms-world-design-assets.html
- https://theblog-adobe.hlx.page/en/drafts/migrated/2017/11/20/make-experience-business.html
- https://theblog-adobe.hlx.page/en/drafts/migrated/2020/04/27/the-state-of-utah-uses-adobe-sign-to-accelerate-telework-during-crisis.html

**Comment by rofe** [comment]
@avanishgandhi I don't see banners in the design redlines. Can we just assume they should look the same as they currently do on theblog.adobe.com?

**Comment by avanishgandhi** [comment]
@rofe - On the redline XD file on page page 35 there is a banner redlined.
![image](https://user-images.githubusercontent.com/62259400/83679312-0d978c80-a594-11ea-8aa5-3b1931163074.png)

https://xd.adobe.com/view/b11a5151-ca60-4c4a-4420-967d97346b2e-c72b/screen/8d912c98-9609-470c-8886-a2f78464f33e/Article-1440-1

**Comment by davidnuescheler** [comment]
i think the new banner designs are not compatible with the content of the actual banners as they exist in the blog today, and were migrated. i would assume that for the sake of the migration and batch-1 we would start with the existing banners and layout for the sake of continuity. 

i would recommend that at a later stage we redesign the existing banners together with a change of the content for the migrated banners, if we want to clean up the banners or alternatively add this new banner layout as a secondary option.

**Comment by davidnuescheler** [comment]
@kptdobe maybe we should give the current banners `legacy-banners` or `migrated-banners`

**Comment by rofe** [comment]
I think this is done and can be closed now.
