### ISSUE TITLE
Customer Quotes (Req 35 from PRD)

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#189]
- Authors need the ability to add customer quotes/testimonials within articles.
- Customer quotes get special design applied to them to make it easier for article reader to consume them
- Need to document how authors will setup new customer quotes in the articles

A.COM Central PRD Repository > CMO + Blogs Migration > image2020-5-8_7-53-34.png

**Comment by avanishgandhi** [comment]
@rofe live examples for customer quotes can be found on the following article

https://cmo.adobe.com/articles/2020/3/effectively-managing-cx-takes-the-right-technology--partners--an.html#gs.5rrhpg

![image](https://user-images.githubusercontent.com/62259400/81591161-d9ec8c80-9370-11ea-91f8-94ae2cbb19e5.png)

**Comment by rofe** [comment]
@avanishgandhi Ok, thanks. But no (known) usages on the US blog, correct?

**Comment by rofe** [comment]
Part of #179

**Comment by rofe** [comment]
Assuming no such quotes are used in the US blog, I'd suggest to move this to batch 2 (CMO & regional blog migration).

**Comment by rofe** [comment]
@avanishgandhi I think this is implemenetd with the blockquote.
