### ISSUE TITLE
Style guide - design redlines provided for updates to be made to the blogs (PRD requirement - 9)

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#190]
@rofe 

 the latest redlined designs have been provided by Design team. We can take this story on for development for styling updates to templates and components
https://xd.adobe.com/view/b11a5151-ca60-4c4a-4420-967d97346b2e-c72b/grid

How do we break this into smaller stories to cover styling updates on templates as well as components?

**Comment by rofe** [comment]
> We can take this story on for development for styling updates to templates and components

Thanks, but I'd suggest to continue with the existing #179 

> How do we break this into smaller stories

If truly needed, you can create new issues and link them to the parent issue by typing `#179`, then they will show up in the timeline there.
