### ISSUE TITLE
Category Templates - Detail Requirements (PRD - REQ9)

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#191]
**Requirements**
* System should support new category pages which show all the articles which are tagged with the category
* Category pages should support a filter for "Product & Technology"
* Category pages should show a grid of article cards which are 4 column across.
* Category pages should have lazy loading feature so the page should always load 4 columns of article cards. User should have a button which shows View more button which allows users to see 4 more rows of results  
* **Category pages have a default marquee image at the top. Optionally dedicated images can be inlined in the Word document**

**Redlined Design URL - https://xd.adobe.com/view/b11a5151-ca60-4c4a-4420-967d97346b2e-c72b/grid**

**Comment by rofe** [comment]
Part of #179

**Comment by davidnuescheler** [comment]
added the custom image featured, see example...

https://staging--theblog--adobe.hlx.page/en/topics/creativity-plus.html

**Comment by rofe** [comment]
Very cool!

**Comment by rofe** [comment]
Done except for filtering

**Comment by rofe** [comment]
Closing now. Filtering handled in #193.
