### ISSUE TITLE
Author Page Template - Detailed Requirements (PRD REQ9)

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#192]
**Requirements**
- System should support new author landing pages which show all the articles which are tagged with given author 
- Author pages should support a filter for "Product & Technology"
- Author pages should show a grid of article cards which are 4 column across.
- Author pages should have lazy loading feature so the page should always load 4 columns of article cards. User should have a button which shows View more button which allows users to see 4 more rows of results
- Author pages should have a blurb about the author which can be centrally managed. The Author profile images should be saved in the following folder - **Documents/theblog/assets/author-profile**

Redlined Design URL - https://xd.adobe.com/view/b11a5151-ca60-4c4a-4420-967d97346b2e-c72b/grid

![image](https://user-images.githubusercontent.com/62259400/81608820-b6830b00-938b-11ea-953d-c33bd9c141d1.png)

**Comment by rofe** [comment]
Part of #179

**Comment by rofe** [comment]
Done except for filtering

**Comment by rofe** [comment]
Filtering is no longer desired by biz on author pages. Closing now.
