### ISSUE TITLE
Change URL to blog.adobe.com

### ISSUE THREAD

**Issue by trieloff** [adobe/theblog#197]
This is a replacement for #134 and a critical go-live task.

Instead of having Fastly serve both the old Wordpress-based blog and the new Helix-powered blog and switch on a per-request basis, we set up a new domain `blog.adobe.com` that will serve the new blog exclusively.

This domain can be used in a soft-launch mode that includes load tests (@rofe) and user acceptance tests, before we complete the switchover (new issue).

The network architecture we are aiming for looks like this:

![Proposal 2: New Domain](https://user-images.githubusercontent.com/39613/81817080-75762c80-952c-11ea-8217-c64d553a31da.png)

Wordpress/Akamai and Helix/Fastly are sitting side-by-side, with one side serving `theblog(images).adobe.com` and the other side serving `blog.adobe.com`

The subtasks that need to be completed are:

- [x] get a CSR from Fastly for `blog.adobe.com`
- [x] request a certificate for `blog.adobe.com`
- [x] upload the certificate to Fastly
- [x] change the Fastly service config to accept traffic at `https://blog.adobe.com`
- [x] set up DNS config for `blog.adobe.com` to point to Fastly IP addresses

/cc @avanishgandhi

**Comment by trieloff** [comment]
Ok, we are ready for the DNS activation.

**Comment by trieloff** [comment]
I will request the DNS change for Monday, 10am Central European summer time.

**Comment by rofe** [comment]
Should we add additional monitoring for `blog.adobe.com` or replace the current `theblog.helix-demo.xyz` one?

**Comment by trieloff** [comment]
https://blog.adobe.com works now. IMS still needs whitelisting.
