### ISSUE TITLE
Handle redirects for old theblog.adobe.com URLs

### ISSUE THREAD

**Issue by trieloff** [adobe/theblog#198]
In switching from `theblog.adobe.com` to `blog.adobe.com` (see #197) we also need to make sure that existing URLs such as 

https://theblog.adobe.com/business-resilience-leading-through-change/ 

get redirected to a new URL like

https://blog.adobe.com/en/2020/04/17/business-resilience-leading-through-change.html 

(@rofe to confirm the new URL pattern)

For that to happen, we need to:

- [x] make sure `blog.adobe.com` is live (#197)
- [x] get a certificate for `theblog.adobe.com` and Fastly
- [x] set up (temporary) redirect rules in Fastly
- [ ] change the DNS for `theblog.adobe.com` to be served from Fastly instead of Wordpress (short TTL)

Once the changes have been confirmed (both the temporary redirects and the DNS change can be rolled back quickly), we make them more permanent.

- [ ] set up (permanent) redirect rules in Fastly
- [ ] change the DNS for `theblog.adobe.com` to be served from Fastly (long TTL)

The resulting architecture would be following:

![Network Architecture The Blog](https://user-images.githubusercontent.com/39613/81818658-9b043580-952e-11ea-84cc-a5dbae7d89e4.png)

/cc @avanishgandhi

**Comment by rofe** [comment]
> (@rofe to confirm the new URL pattern)

Confirmed.

@avanishgandhi does this issue replace #168 or is it compementary?

**Comment by avanishgandhi** [comment]
I think this is complementary. At the end there will be a single 301 redirect artifact which we will need to manage for everything that gets migrated to the new platform. This one is more specific to theblog.

**Comment by rofe** [comment]
@trieloff would be great if you could drive this forward. I think this is a must-have for a batch-1 go-live end of June, otherwise we won't get any traffic from legacy articles.

**Comment by kptdobe** [comment]
Not the issue but related: 

https://blog.adobe.com/business-resilience-leading-through-change

redirects to 

https://blog.adobe.com/en/archive/2020/04/07/business-resilience-leading-through-change.html

which is wrong. Correct url is

https://blog.adobe.com/en/drafts/migrated/2020/04/07/business-resilience-leading-through-change.html

**Comment by trieloff** [comment]
So the URL pattern is:

1. `https://blog.adobe.com/en/:yy/:mm/:dd/:slug.html` as @rofe confirmed
2. `https://blog.adobe.com/en/drafts/migrated/:yy/:mm/:dd/:slug.html` as  @kptdobe says
3. `https://blog.adobe.com/en/archive/:yy/:mm/:dd/:slug.html` as @trieloff implemented
4. something else

? 🤷‍♀️

**Comment by kptdobe** [comment]
Today, I think @kptdobe is correct.

But... this made me think to something else: the migrated content is under `/en/drafts/migrated/:yy/:mm/:dd/` but the published content will be in `/en/publish/:yy/:mm/:dd/`
So `/en/drafts/migrated/:yy/:mm/:dd/` is a temporary state and once approved, the content should be move to `/en/publish/:yy/:mm/:dd/`.

Conclusion: the correct url should be `https://blog.adobe.com/en/publish/:yy/:mm/:dd/:slug.html`.

But, maybe... we do not want `publish` to appear in the urls... :)
So finally, maybe @rofe is correct with his `https://blog.adobe.com/en/:yy/:mm/:dd/:slug.html`. 

Good luck with that 😂

**Comment by trieloff** [comment]
And now I suddenly remember why I have been procrastinating this task 😭

**Comment by kptdobe** [comment]
Considering how many times he changed the url logic / headers in `helix-pages` (canonical or not canonical url), my vote goes to @rofe to make the right decision!

**Comment by rofe** [comment]
Keeping the issue open until the DNS switch is complete.

**Comment by rofe** [comment]
Will open a separate issue for the DNS switch.
