### ISSUE TITLE
Taxonomy: user-facing and non-user-facing tags

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#211]
We currently only differentiate between topics and products when it comes to rendering them:
- Topics and products get added to the metadata
- Topics get displayed and linked
- Products are not displayed or linked 

We now also have a need to differentiate between user-facing and non-user-facing topics:
- User-facing tags get displayed and linked
- Non-user-facing topics - like products - are not displayed or linked

All kinds of topics and products still get added to the metadata.

**Comment by rofe** [comment]
When handling topics in a post, we could request `/{lang}/topics/_taxonomy.plain.html` which is the single source of truth and contains separate lists for user-facing and non-user-facing-tags. Based on that document, we decide to either display or hide a topic.

**Comment by davidnuescheler** [comment]
as far as i understood the conversation the distinction between user facing and non-user facing was primarily on whether they show up in the navigation. so i don't know that for the tagging there needs to be a a distinction.

**Comment by rofe** [comment]
cc @kptdobe

**Comment by rofe** [comment]
Latest consensus is to surface all tags.
