### ISSUE TITLE
Rename "Topic" to "Category"

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#215]
With https://github.com/adobe/theblog/issues/191 and the current discussions on the NUFT (https://github.com/adobe/theblog/issues/211), it seems that Category is the new name for Topic. The folders, code... should be renamed accordingly.

I would still wait a bit for final acceptance.

Here is the impact:

- [ ] 'Topics:' string in post entries becomes 'Categories:'
  - [ ] indexer must be adjusted
  - [ ] importer must be adjusted
- [ ] Categories will be stored under `/en/categories` folder in Sharepoint (vs `/en/topics` at the moment)
- [ ] **URLs for category pages will be `/en/categories/<category>.html` (vs `/en/topics/<topic>.html` at the moment)**
- [ ] theblog code adapted (new url space, variable names, page type detection...)

Considering the number of changes, we need to make sure this is a validated and approved decision. The most impactful change is the URL space: when we go live, Google will index the category pages and new rename will have a stronger impact (we'll need url mapping)

@avanishgandhi could you please make sure we get the final approvement ?

cc @rofe

**Comment by rofe** [comment]
@avanishgandhi this rename should be approved or denied prior to go-live

**Comment by davidnuescheler** [comment]
i think this is really an implementation detail, so i definitely not attach this to batch-1. especially as it is quite some work to get this done and it has close to zero user exposure.

**Comment by rofe** [comment]
Closing for now.
