### ISSUE TITLE
split js (and possibly css) into sync and defer

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/theblog#218]
currently we inline a non-trivial amount of js in head.html for the sake of sync execution
this should probably be moved to an external file for esthetic and caching reasons.
the same may apply to lesser degree to css.

**Comment by rofe** [comment]
I think we could even take this a step further and avoid loading post-specific JS on the homepage and vice-versa. We'd keep the common functions in script.js and have it load one of the following based on the page type:
- homepage.js
- article.js
- topic.js
- author.js

We could follow the same principle for CSS.

**Comment by rofe** [comment]
I created 2 PRs for this: #221 for the JS split and #222 for JS and CSS. Neither of them brought the desired Lighthouse score boost, unfortunately.

**Comment by rofe** [comment]
Merged both after reviewing them with @davidnuescheler.
