### ISSUE TITLE
improve lazy loading MutationObserver

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/theblog#219]
currently the `MutationObserver` is probably also catching all the manipulations we do after `DOMContentLoaded` which produces unnecessary image flashes for images that are added via js with the correct `?width=`...

the easiest way to fix this would be disconnect the observer on `DOMContentLoaded` or ignore everything that already has a `?width=`.

having said that, i think there is a real potential here to make this a lot more general purpose and exact image loading by using `window.getComputedStyle()` and effectively load the actually correct size needed as defined in the style.

**Comment by rofe** [comment]
In my tests back then, it didn’t manipulate anything added via JS. But of course I’m open to improvements 🙂
