### ISSUE TITLE
helix query: title selector too inclusive

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/theblog#220]
we had a `h1:first-of-type` as the select for the title field in `helix-query.yaml` which led to issues as embeds started to include additional `h1`s which is probably a semantic issue to begin with @kptdobe 

however short-term i made the selector a little bit more specific... check here:
https://github.com/adobe/theblog/commit/e610a3586fc5cd2c6fccc911f56e83f834083f68

as i don't have a good way to test this, i wanted to see if @dominique-pfister or @tripodsan could take a look to make sure that i didn't break it...

.ps: after committing, i actually think the selector should be `main > div:first-of-type > h1:first-of-type`

**Comment by dominique-pfister** [comment]
Sure, will have a look!

Note, that I added the XL index definition to 'helix-query.yaml' in 'excel-index' branch. The result of indexing one file (en/drafts/migrated/2018/12/21/the-data-is-wrong-or-is-it.md) can be seen in the index.xlsx on the last line (row 22). Any suggestions on the format of the cells (this is mostly innerHTML) are more than welcome.

If you feel brave and want to index other files, open a terminal, switch to the 'helix-index' namespace and invoke the OW action:

$ set WSK_CONFIG_FILE=~/.wskprops.d/helix-index # or other command to switch to helix-index
$ wsk action invoke helix-services/index-files@1.1.29 -p owner adobe -p repo theblog -p ref excel-index -p branch excel-index -p path <your path> -r

I'll set up the automatic "index-on-change" mechanism soon!

Cheers
Dominique

________________________________________

**Comment by rofe** [comment]
Currently leads to this on the homepage:
![image](https://user-images.githubusercontent.com/1609742/84056025-eedf2e80-a9b5-11ea-8246-fb46383bbe8f.png)

**Comment by rofe** [comment]
@dominique-pfister https://github.com/adobe/theblog/commit/e610a3586fc5cd2c6fccc911f56e83f834083f68 is now in master, can you re-run the indexer?

**Comment by dominique-pfister** [comment]
Re-ran the indexer on 7PM CEST, 83 items with title containing *19* were processed. Home page looks ok, now.

Put the automatic index-on-change mechanism back online.
