### ISSUE TITLE
Correct URLs in global navigation

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#240]
The following wrong URLs have been found and need to be adjusted:

**Adobe Blog Logo**
actual: `#`
expected: `/`

**Insights & Inspiration**
- Trends & Research
  actual: `/en/topics/trends-research.html`
  expected: `/en/topics/trends--research.html` (see also https://github.com/adobe/helix-theblog-importer/issues/61)
- Leader Perspectives
  actual: `/en/topics/leaders-perspectives.html`
  expected: `/en/topics/leader-perspectives.html`

**Responsibility**
- Diversity & Inclusion
  actual: `/en/topics/diversity-inclusion.html`
  expected: `/en/topics/diversity--inclusion.html`
- Data & Privacy
  actual: `/en/topics/data-privacy.html`
  expected: `/en/topics/data--privacy.html`

**Adobe Culture**
- None of these topics currently exist on the site, meaning there are no articles with such tags. Should those links rather point to `www.adobe.com/*`?

**Featured article**
- Business Resilience: Leading through Change
  actual: `/`
  expected: `/en/2020/04/07/business-resilience-leading-through-change.html`

**Comment by avanishgandhi** [comment]
@rofe I have made the updates - https://cc-author.prod.corp.adobe.com/content/globalnav/us/en/blog-gnav.html?wcmmode=disabled

**Comment by rofe** [comment]
@avanishgandhi cool! A few more suggestions:
- don't use the full URL on the logo link, just `/` - this will ensure it will also work on staging URLs without moving the user to prod
- Leaders Perspective - the link text still has leaders in plural instead of singular
- Read article (featured article) link still points to homepage instead of the article (see above for the link)
- The entire Adobe Culture menu won't work because those aren't actual topics. See also above.

**Comment by rofe** [comment]
- Created the missing topic pages from the **Adobe Culture** menu.
- Logo link stays as is for now
