### ISSUE TITLE
Switch DNS for theblog.adobe.com

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#245]
From #198: change the DNS for `theblog.adobe.com` to be served from Fastly instead of Wordpress (short TTL).

**Comment by trieloff** [comment]
When?

**Comment by rofe** [comment]
The date is a moving target, but currently scheduled for Mon 7/27, see #238.

**Comment by rofe** [comment]
For the record: we'll need a reliable way to access the WP instance after the switch (IP or alternative hostname) so we can continue to import content.

cc @kptdobe

**Comment by kptdobe** [comment]
I created https://github.com/adobe/helix-theblog-scanner/issues/5 and https://github.com/adobe/helix-theblog-importer/pull/69 for the importer to use the IP when requesting the server. I made the changes but it is very slow... not sure if the Runtime invocation will not timeout. Need to keep an eye on it.

**Comment by rofe** [comment]
https://theblog.adobe.com now redirects to https://blog.adobe.com
