### ISSUE TITLE
Suppress age: header in outer CDN

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/theblog#253]
currently we leak the `age:` header in responses from the outer CDN to the browser.

as this is reflective of the age of the cache in the CDN it is not to be interpreted by the browser we should make sure that it is not set.

having the `age:` header set beyond `cache-control: max-age` is effectively resulting in a `no-cache` on the browser side, which is definitely not intended.

**Comment by trieloff** [comment]
Potential fix here: https://github.com/adobe/helix-publish/pull/509
