### ISSUE TITLE
Index articles without extension

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#271]
The indexer currently indexes articles with `.html` extension. Since https://github.com/adobe/helix-dispatch/issues/267 it is possible to request URLs without extension. It would be nice to omit the extension in the theblog index as well.

**Comment by dominique-pfister** [comment]
That blows the `objectID` generation which is currently based on the path of the file. Is that really necessary?

**Comment by tripodsan** [comment]
what is the benefit of having the path w/o extension in the index?

**Comment by rofe** [comment]
I think this boils down to individual taste 😉  the paths in the index define the article links on the blog homepage as well as the URLs Google will index based on the sitemap.xml, so... in summary the URLs we want to expose to visitors. And yes, if you asked @davidnuescheler, I think the canonical path should eventually also be extension-less, but that's probably part of a larger discussion.

**Comment by davidnuescheler** [comment]
yeah, i think that any external reference should not have a `.html` extension, they just look antiquated.

**Comment by tripodsan** [comment]
but you can easily remove the `.html` extension when reading from the index. but having both variants indexed makes no sense.

**Comment by rofe** [comment]
I agree with @tripodsan, this could be done on the client side.
