### ISSUE TITLE
Requesting a page with a `=` in its path returns a 403

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/theblog#276]
It seems we have another candidate character to allow in a URL path:

- https://theblog-adobe.project-helix.page/en/publish/2020/07/13/p=93010.html

Requesting this path returns a 403, because the `=` character is not allowed in a path (outside the query string). This looks like another character we need to allow as we already did allow some in https://github.com/adobe/theblog/issues/260

**Comment by rofe** [comment]
@dominique-pfister Is this a real life or theoretical problem? If the latter, I would defer (close) this for now.

**Comment by dominique-pfister** [comment]
The document mentioned in the issue description above can not be delivered but generates a 403, so yes, I think this should be either fixed or the document renamed.

**Comment by rofe** [comment]
Ah, I thought that was just an random example 😂  
I'll fix that file name for now. The title in the document is something completely different...
@kptdobe do you know how this could have happened during importing?

**Comment by rofe** [comment]
Fwiw, the original was https://theblog.adobe.com/four-things-your-dam-should-do-beyond-simply-managing-your-assets/
