### ISSUE TITLE
Category page should include child categories

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#279]
When tagging a story with the tagger or via the import, only the leaf categories are set on the document. For example, a story can be tagged as `Creative Inspirations & Trends` which based on the taxonomy document belongs to `Insights > Creativity & Design > Creative Inspirations & Trends`. 
In the navigation, when a user clicks on `Insights`, this story should appear in the list. Same for `Creativity & Design` and `Creative Inspirations & Trends`. This is not the case today because when we index, we do not consider the parent categories.

cc @davidnuescheler @dominique-pfister 

This also related to #278

**Comment by kptdobe** [comment]
Or maybe this is not an indexing issue but just the logic that loads the posts on the `Insights` and `Creativity & Design` which should first read the taxonomy document and load the posts with the category and its children.

**Comment by dominique-pfister** [comment]
If that taxonomy information is easily retrievable in that step, then yes, it sounds plausible, to have it fill the missing topic entries instead of implementing this project specific requirement in the indexer.

**Comment by kptdobe** [comment]
Doing it client side is straight forward. Almost done.

**Comment by kptdobe** [comment]
The latest PR is not enough: we also need to compute the parent topics for each post to know their full list of topics.
