### ISSUE TITLE
[Products] Create product pages and update fetchProduct

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#28]
Follow up from #14.

Current product handling is ok for demo (links are not all working) but final implementation should be different: it should follow the same pattern than author, fetch the product page, retrieve logo / link / product name from product page and insert it from here. Creating all corresponding content in OneDrive is a fastidious task (all logo should be pasted inside the docx), will be done when architecture is clear and final.

Todos: once final destination system is defined (OneDrive, GoogleDoc or GitHub)

- [ ] create a product page per product which includes: logo, product name, link to adobe.com page
- [ ] update `fetchProducts` from `head.html` to gather data from product page (instead of guessing logo name and link).

**Comment by kptdobe** [comment]
The product page is not an ideal solution neither. Some pages have 9 products referenced, it would mean 9 extra requests to just to fetch the links and icons.

**Comment by rofe** [comment]
Product pages are no longer part of the project. Closing.
