### ISSUE TITLE
Prepare for upcoming response change for query.json

### ISSUE THREAD

**Issue by tripodsan** [adobe/theblog#284]
see https://github.com/adobe/helix-content-proxy/issues/121

**Comment by davidnuescheler** [comment]
https://github.com/adobe/theblog/blob/537f19c34be6bcb232255532f1759c5659acd6a2/scripts/common.js#L295-L298

**Comment by davidnuescheler** [comment]
oh wow, i botched it ;)

**Comment by davidnuescheler** [comment]
https://github.com/adobe/theblog/blob/9e6d3dbbc14fdd0d1e9e520cc1f23d5c01adeb02/scripts/common.js#L294-L298

**Comment by rofe** [comment]
@davidnuescheler is there something left to do here or can this be closed?

**Comment by davidnuescheler** [comment]
this can be closed
