### ISSUE TITLE
Some posts have no article body

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/theblog#292]
The following items have a teaser that starts with `Topics: ...`, indicating that there is no article body to extract a teaser from:
- en/publish/2017/11/10/artificial-intelligence-puts-ai-personalization.html
- en/publish/2017/11/03/effective-content-marketing.html
- en/publish/2017/10/24/tackling-offline-blind-spot.html
- en/publish/2017/09/22/redefining-retail-experience.html
- en/publish/2017/09/15/time-move-beyond-smartphone.html
- en/publish/2017/09/08/double-edged-sword-adtech-martech.html
- en/publish/2017/09/01/youve-got-mail-email-marketing-stay.html
- en/publish/2017/08/25/lights-camera-action-live-video-digital-marketing.html
- en/publish/2017/08/18/digital-marketing-world-altered-reality.html
- en/publish/2017/08/04/trash-treasure-paint-marketing-success-creative-email-design.html
- en/publish/2017/07/28/marketing-jackpot-personalization-scale.html
- en/publish/2017/07/26/follow-these-steps-to-not-be-paralyzed-by-your-data.html
- en/publish/2017/07/14/virtual-reality-future-marketing.html
- en/publish/2017/06/30/understanding-achieving-data-analytics-maturity.html
- en/publish/2017/06/23/enhancing-customer-experience-brand-partnerships.html
- en/publish/2017/06/16/changing-the-traditional-advertising-channel.html
- en/publish/2017/06/09/unifying-message-cross-channel-campaigns.html
- en/publish/2017/06/02/connecting-industry-academia-bright-future-data-science.html
- en/publish/2017/05/26/hey-marketers-bots-coming.html
- en/publish/2017/05/19/content-marketing-content-experience.html
- en/publish/2017/05/12/build-unstoppable-business-customer-experience-optimization.html
- en/publish/2017/05/05/sky-limit-travel-industry-goes-digital.html
- en/publish/2017/03/24/become-experience-led-business.html
- en/publish/2017/02/17/need-know-cornerstone-data-driven-marketing-data-management-platforms.html
- en/publish/2016/12/02/data-science-digital-marketing-match-made-heaven.html
- en/publish/2016/11/18/impact-dynamic-creative-optimization-programmatic-advertising.html
- en/publish/2016/10/28/let-big-data-make-big-difference-marketing.html
- en/publish/2016/09/30/future-tv-advertising-golden-era-digital.html
- en/publish/2016/08/26/bridging-marketing-iot.html
- en/publish/2016/08/12/email-marketing-for-the-win-how-to-do-email-right.html
- en/publish/2016/06/14/adobechat-experience-business.html
- en/publish/2016/06/08/prayasam-creative-catalyst-spotlight.html

**Comment by kptdobe** [comment]
After today import, the list is:

- en/publish/2016/06/08/prayasam-creative-catalyst-spotlight.html
- en/publish/2017/05/05/sky-limit-travel-industry-goes-digital.html
- en/publish/2017/08/18/digital-marketing-world-altered-reality.html
- en/publish/2017/11/10/artificial-intelligence-puts-ai-personalization.html
- en/publish/2017/07/14/virtual-reality-future-marketing.html
- en/publish/2017/11/03/effective-content-marketing.html
- en/publish/2017/06/23/enhancing-customer-experience-brand-partnerships.html
- en/publish/2017/08/25/lights-camera-action-live-video-digital-marketing.html
- en/publish/2017/09/22/redefining-retail-experience.html
- en/publish/2018/11/26/a-picture-is-worth-a-million-data-points.html
- en/publish/2017/10/24/tackling-offline-blind-spot.html
- en/publish/2017/01/11/2017-the-year-performance-reviews-get-the-axe.html
- en/publish/2017/12/13/adobe-girls-technology-summit-london-inspiration-laughter-learning.html
- en/publish/2017/07/28/marketing-jackpot-personalization-scale.html
- en/publish/2017/05/12/build-unstoppable-business-customer-experience-optimization.html
- en/publish/2017/09/15/time-move-beyond-smartphone.html
- en/publish/2017/05/26/hey-marketers-bots-coming.html
- en/publish/2017/05/19/content-marketing-content-experience.html
- en/publish/2016/08/26/bridging-marketing-iot.html
- en/publish/2016/06/14/adobechat-experience-business.html
- en/publish/2017/09/01/youve-got-mail-email-marketing-stay.html
- en/publish/2017/06/09/unifying-message-cross-channel-campaigns.html
- en/publish/2017/08/04/trash-treasure-paint-marketing-success-creative-email-design.html
- en/publish/2017/03/24/become-experience-led-business.html
- en/publish/2016/08/12/email-marketing-for-the-win-how-to-do-email-right.html
- en/publish/2017/06/02/connecting-industry-academia-bright-future-data-science.html
- en/publish/2017/06/30/understanding-achieving-data-analytics-maturity.html
- en/publish/2017/07/26/follow-these-steps-to-not-be-paralyzed-by-your-data.html
- en/publish/2016/12/02/data-science-digital-marketing-match-made-heaven.html
- en/publish/2017/02/17/need-know-cornerstone-data-driven-marketing-data-management-platforms.html
- en/publish/2016/10/28/let-big-data-make-big-difference-marketing.html
- en/publish/2017/06/16/changing-the-traditional-advertising-channel.html
- en/publish/2017/09/08/double-edged-sword-adtech-martech.html
- en/publish/2016/11/18/impact-dynamic-creative-optimization-programmatic-advertising.html
- en/publish/2016/09/30/future-tv-advertising-golden-era-digital.html

**Comment by kptdobe** [comment]
I'll share the list of real empty pages with theblog team.

**Comment by kptdobe** [comment]
Re-opening since Matt said those "empty" pages can be removed.

**Comment by kptdobe** [comment]
What needs to be done here:
- delete the articles with an empty body (2nd list)
- the redirect (for example https://blog.adobe.com/future-tv-advertising-golden-era-digital) needs to go to homepage and not 404.

**Comment by rofe** [comment]
@avanishgandhi I think this should be turned into a task for the content team (i.e. jira or wiki)

**Comment by rofe** [comment]
@avanishgandhi this is a left-over from batch-1: we should either remove these empty articles from the `raw_index` sheet (and create redirects for them to go the homepage as suggested by @kptdobe) - or close this issue as won't fix.
