### ISSUE TITLE
New Feature - Interlinking Capability in Helix

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#293]
SEO team has a request to add the ability to add theme relevant click links to blog article content. 

- SEO team would like to manage the keyword and link content through a spreadsheet of some sorts where they can regularly add, update keywords  
- System should support interlink updates to all new blog articles created on the Helix platform. The links can be added during publishing process (instead of at every update to minimize how many times we run a script to add links)
- System should support application of links on all migrated content from theblog.adobe.com, CMO.adobe.com and all the other blogs sites. 

@rofe @davidnuescheler - this is based on the email discussion we had on july 16 and july 17th.

**Comment by trieloff** [comment]
Does this mean that all occurrences of a certain word or phrase that are found in a spreadsheet should be linked to a URL provided in said spreadsheet?

**Comment by davidnuescheler** [comment]
almost, the first instance of each term per document should be linked.

i think this is something that is fairly blog specific and should be implemented as a helped that can be run against a single `.docx` and as the spreadsheet changes against all `.docx` & `.md`

**Comment by rofe** [comment]
Trying out a client-side approach first

**Comment by rofe** [comment]
The client-side approach seems to work really well, plus brings the advantage that keywords and URLs can be changed at any time without needing to purge cached article pages. Some examples:
- https://interlink--theblog--adobe.hlx.page/en/publish/2020/08/31/merkle-ceo-shifting-marketing-budgets-priorities-covid19.html
- https://interlink--theblog--adobe.hlx.page/en/publish/2020/08/13/smb-playbook-for-customer-experience-management.html
- https://interlink--theblog--adobe.hlx.page/en/publish/2020/08/11/adobe-analytics-introduces-mobile-app.html

Feel free to browse more articles on https://interlink--theblog--adobe.hlx.page and let me know here if you see any weird stuff.

@avanishgandhi: the feature is based on the Excel workbook `en/keywords.xlsx` which currently contains a bunch of data that looks like it should be reviewed and cleaned up before we go live with this feature. Could you follow up with the right folks?

**Comment by avanishgandhi** [comment]
@rofe for sure. let me check it out and take it to Matt and team.
thanks
Avanish

**Comment by rofe** [comment]
@avanishgandhi `en/keywords.xlsx` is now curated. Do you think this feature is now ready to be merged into the staging branch?

**Comment by avanishgandhi** [comment]
@rofe I check the top 3 links provided in this ticket above and they look good to me. I think we can move this forward into staging so we can have Giselle test is once too.

thanks

**Comment by rofe** [comment]
@avanishgandhi this can now be reviewed in staging: https://staging--theblog--adobe.hlx.page/
