### ISSUE TITLE
DOTCOM-25393 - Accessibility: Filter dropdown needs proper focus management

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#294]
https://jira.corp.adobe.com/browse/DOTCOM-25393?src=confmacro

**Context** 

Chrome Version 83.0.4103.116 on macOS. MacBook Pro running macOS Catalina 10.15.5

**URL**: https://blog.adobe.com/en/topics/news.html

**Reproduction steps:**

Go to URL above tab through the page to reach filter dropdown
In order to see that the keyboard focus is on the dropdown, you need to first add focus indicator styling to it.
Once that's done, place keyboard focus on the dropdown button and press enter
It opens the popup.
Press tab to enter the dropdown.
Make selections and close the dropdown using Esc key.
Dropdown closes but keyboard focus doesn't seem to go back to the dropdown button.
Expected behavior

Make sure upon closing the popup(Using Esc key), keyboard focus goes back to triggering button.

Dropdown button should also use aria-haspopup to convey the presence/ability to trigger a popup

Refer to https://www.w3.org/TR/wai-aria/#aria-haspopup

**WCAG Success Criteria**

Keyboard

**Comment by avanishgandhi** [comment]
I have asked QA to test and close the story in JIRA

**Comment by avanishgandhi** [comment]
**More comments from the tester**
Focus indicator part of the problem(Reproduction step #2) is fixed. But the keyboard focus doesn't go back to triggering button when dropdown is closed. Please check reproduction steps 5-7 and expected behavior again.

**Comment by avanishgandhi** [comment]
@davidnuescheler can we please reopen this issue. I can reopen it.

**Comment by rofe** [comment]
@avanishgandhi Keyboard focus is now on the button after closing the dropdown, and keyboard access using ESC and Enter is enhanced. Please re-test in the staging branch.
