### ISSUE TITLE
DOTCOM-25387 - Tab order does not match reading order on pages with posts

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#296]
https://jira.corp.adobe.com/browse/DOTCOM-25387?src=confmacro

**Context** 
Chrome Version 83.0.4103.116 on macOS. MacBook Pro running macOS Catalina 10.15.5

**Reproduction Steps:**

Open any page with a blog post. For ex: https://blog.adobe.com/en/2020/07/14/cios-face-their-next-biggest-challenge.html#gs.azje5a
Tab through the page and you'll notice that user will go through the links in article first and then is taken back to the post-header. That's because header markup for all articles is placed after the image and post body.
Expected behavior:

Tab order and reading order should always match. So, please move the markup to reflect the reading order. 

**WCAG Success Criteria**
Keyboard

**Comment by davidnuescheler** [comment]
hmm... works for me, also the DOM looks like it is in the right order. @avanishgandhi can you check this, and see if this still persists? otherwise feel free to close this one...

**Comment by avanishgandhi** [comment]
It works now. It was not in that order when i check last time. Will ask QA to confirm
