### ISSUE TITLE
Gifs do not render, only show URL

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#300]
JIRA ticket - https://jira.corp.adobe.com/browse/DOTCOM-25678

**Detailed Description:** Gifs in article expected to render – in this piece, meme-like gifs – instead only show links to giphy.com
................................
**URL**: https://blog.adobe.com/en/2019/05/01/10-reasons-to-drop-what-you-are-doing-and-register-for-imagine-now.html#gs.bh8qcl
................................
**Steps to Reproduce:**
1. Open URL
2. Scroll to list, and see giphy links
Expected Results: links don't show, the gif animations do. see image
................................
**Actual Results:**

![image](https://user-images.githubusercontent.com/62259400/88303808-4dd5da00-ccbc-11ea-8ab9-5b9df83ca4db.png)

**Comment by rofe** [comment]
Confirmed working in prod (thanks @MarquiseRosier!). Closing.
