### ISSUE TITLE
DOTCOM-25677 - Header image cuts off

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#301]
JIRA - https://jira.corp.adobe.com/browse/DOTCOM-25677

Detailed Description: Header image cuts off the sides, cutting into text on the image. 
................................
URL: https://blog.adobe.com/en/2020/05/22/a-look-inside-box-of-motion.html#gs.bh8mgt
................................
Steps to Reproduce:
1. Open URL
2. See header image cut off on sides so we dont see the whole message as intended
Expected Results: Full text on image can be seen/read
................................
Actual Results: Image is cut off on both sides. See image

![image](https://user-images.githubusercontent.com/62259400/88304882-aeb1e200-ccbd-11ea-820d-14bb9894ca82.png)

**Comment by avanishgandhi** [comment]
This could be a common issue for many images. Should we look at importing these images from Wordpress? Or a hybrid solution to only update these images for newer content?

**Comment by davidnuescheler** [comment]
as per conversation, i am relaxing the fixed height constraint.

**Comment by davidnuescheler** [comment]
check out here: https://staging--theblog--adobe.hlx.page/en/publish/2020/05/22/a-look-inside-box-of-motion.html#gs.bk7k0p

**Comment by rofe** [comment]
This seems to be fixed. Closing.
