### ISSUE TITLE
DOTCOM-25665 - Linkedin embedded video doesn't embed

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#302]
**JIRA URL** - https://jira.corp.adobe.com/browse/DOTCOM-25665 

**Detailed Description**: Imbedded video from Linkedin (a Linkedin Live video) is expected to be embedded in the blog post to watch. Instead, there is just a link. See image
................................
**URL**: https://blog.adobe.com/en/2020/05/22/why-an-empathetic-digital-experience-matters-more-now-than-ever.html#gs.bha1f2
**Original URL** - https://theblog.adobe.com/why-an-empathetic-digital-experience-matters-more-now-than-ever/
................................
**Steps to Reproduce:**
1. Load URL and scroll down to after the 2nd graf
2. Where it shows a "Linkedin" link, there should be a video frame to watch
3.
Expected Results: An embedded video like a YT video, is on screen to watch. 
................................
Actual Results: A placeholder text "Linkedin" link shows in its place.

migrated article - ![image](https://user-images.githubusercontent.com/62259400/88308152-8b893180-ccc1-11ea-80b7-d6ee1ff6ed4d.png)

original article - ![image](https://user-images.githubusercontent.com/62259400/88308183-9774f380-ccc1-11ea-82de-d08f04fbe407.png)

**Comment by MarquiseRosier** [comment]
@avanishgandhi the link being imported from that article is the wrong one! 
This is the correct one: 

##Correct Link
https://www.linkedin.com/posts/adobe-experience-cloud_innovation-and-empathy-in-a-digital-only-activity-6668968801431887872-XCza

##Imported Link
https://www.linkedin.com/video/embed/live/urn:li:ugcPost:6668968795341774848

**Comment by MarquiseRosier** [comment]
@avanishgandhi I fixed this for you!

 It appears that the original blog actually used the Linkedin embed generator; which IFramely can't detect. We have a few embeds that don't work out of the box with Iframely, that we custom built; having done this before for Lottifiles support, I'd be glad to build one such that a link to a Linkedin Post with video will render an embed as generated by Linkedin!

**Comment by rofe** [comment]
@MarquiseRosier I think that would be cool!
