### ISSUE TITLE
DOTCOM-25656 - External link does not open in new tab; Body text too close to feature image caption

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#304]
**JIRA URL** - https://jira.corp.adobe.com/browse/DOTCOM-25656?src=confmacro

**Detailed Description**: The one link to EJI opens in the same window as blog post when clicked; we need it to open in new tab. Additionally, the body text is right under the feature image caption listing the artist. We need more space between body text and the header image caption
................................
**URL**: https://blog.adobe.com/en/2020/06/10/listening-learning-and-taking-action.html#gs.bh4pti
................................
**Steps to Reproduce:**
1. When link opens, notice the "Artwork by Robert Generette III (@Rob_Zilla_III on Twitter)" right above first line of blog post
2. Scroll to 7th graf and click link to EJI, click it. 
3. You leave the page
Expected Results: More space between header of blog post and body of blog post. Even just one more line space; all external links open in new tabs to keep audience on our site.
................................
**Actual Results:** Words look scrunched. External links open for readers but do not take them away from our site.

![image](https://user-images.githubusercontent.com/62259400/88328538-71f5e300-ccdd-11ea-96ac-e01f6bf17259.png)

**Comment by davidnuescheler** [comment]
i didn't see any of this in the requirements or specification. easy to fix, but i don't think `batch-1`.
do we want all external links to open a new window? and does external mean outside *.adobe.com or outside blog.adobe.com?

**Comment by davidnuescheler** [comment]
added some spacing and opening all external links in a new tab, check here:

https://staging--theblog--adobe.hlx.page/en/publish/2020/06/10/listening-learning-and-taking-action.html

**Comment by davidnuescheler** [comment]
...after talking to Matt i will change this to also open adobe.com links in a new window.

**Comment by avanishgandhi** [comment]
Links are not opening in a new window for adobe.com links
