### ISSUE TITLE
DOTCOM-25664 - Image captions are wrong size

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#305]
**JIRA URL** - https://jira.corp.adobe.com/browse/DOTCOM-25664?src=confmacro

**Detailed Description**: Image captions look like regular body text. When near text and image, it's unclear whether it's an actual caption or not
................................
**URL**: https://blog.adobe.com/en/2020/06/23/a-software-bugs-life-how-a-glitch-in-the-code-revolutionized-live-animation.html#gs.bh9qgq
................................
**Steps to Reproduce:**
1. Open URL
2. Scroll to images
3. Note sentence under images are not body text, though they are same size and font. 
Expected Results: Caption text should be smaller and italicized if possible 
................................
**Actual Results:** Image caption text is same size look and feel of all article body text.

**Comment by avanishgandhi** [comment]
While this can be probably updated trough authoring, the issue is seen in every instance on all articles. It would be great to programmatically fix this.

Designs shows example of image caption which has different font as well as spacing which. Both these seem to be the issue.
![image](https://user-images.githubusercontent.com/62259400/88330159-d87c0080-ccdf-11ea-814e-91f5a4fa49bb.png)

**Comment by davidnuescheler** [comment]
sounds good. definitely something that should not be done in authoring, but just a styling change.

**Comment by davidnuescheler** [comment]
should be fixed... check here: https://staging--theblog--adobe.hlx.page/en/publish/2020/06/23/a-software-bugs-life-how-a-glitch-in-the-code-revolutionized-live-animation.html#gs.bk8rll

**Comment by rofe** [comment]
Confirmed fixed in prod as well.
