### ISSUE TITLE
DOTCOM-25660 - Adobe.ly link not clickable

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#306]
JIRA URL - https://jira.corp.adobe.com/browse/DOTCOM-25660?src=confmacro

**Detailed Description:** shortened Adobe.ly link is not clickable. Not sure if this happens in many different places, but when the article got migrated, this should be have been translated into a link
................................
**URL**: https://blog.adobe.com/en/2020/04/14/using-creativity-to-honorheroes-doing-extraordinary-things-during-covid-19.html#gs.bh8tiy

**legacy URL :** https://theblog.adobe.com/using-creativity-to-honorheroes-doing-extraordinary-things-during-covid-19/
................................
**Steps to Reproduce:**
1. Open URL
2. Scroll to right after the embedded video
3. See the "https://adobe.ly/heroes" text as an unclickable link
Expected Results: Link should be clickable, opening a new tab
................................
**Actual Results:** Link is plain text and not an actual link

**Comment by davidnuescheler** [comment]
seems like a one off, so i fixed it in content.

https://blog.adobe.com/en/publish/2020/04/14/using-creativity-to-honorheroes-doing-extraordinary-things-during-covid-191.html

**Comment by rofe** [comment]
Fixed in prod.
