### ISSUE TITLE
DOTCOM-25658 - Auto-links ported from old site go to wrong destinations; links open in same window

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#307]
JIRA URL - https://jira.corp.adobe.com/browse/DOTCOM-25658?src=confmacro

**Detailed Descriptio**n: SEO-driven autolinks on blog posts on theblog.adobe.com, were supposed to come over to new blog.adobe.com. In this article, there are missing auto-links, and some go to incorrect destinations. Additionally, external link is not opening in new tab. Article is also missing a legacy tag at the bottom: "Customer Experience"
 ................................
 **URL**: [https://blog.adobe.com/en/2020/06/23/business-australia-relaunches-just-in-time-to-help-businesses-cope-during-covid-19.html#gs.bh59tv]
 ................................
 **Steps to Reproduce:**
 1. Open link
 2. Scroll to 10th graf; click on 'content management system'
 3. In original article, the link goes here: [https://www.adobe.com/experience-cloud/glossary/content-management-system.html] It does not. 
4. Scroll to 12th graf - "publishing" should be a link to here: [https://www.adobe.com/creativecloud/tools/desktop-publishing-software.html]
5. Scroll the 13th graf - "analytics" should link to here: [https://www.adobe.com/experience-cloud/glossary/analytics.html.
|https://www.adobe.com/experience-cloud/glossary/analytics.html]6. Neither publishing nor analytics is actually linked. 
7. There should be a "Customer Experience" tag at the bottom of the article. 

 **Expected Results:** Links go to SEO-approved pages for autolinking. All autolinks from previous article is on new version. Legacy tag from article is on new article. 
 ................................
 **Actual Results:** External link goes to wrong place. Not all the external links from original article are in new article. "Customer Experience" (legacy) tag should be on this article.

**Comment by avanishgandhi** [comment]
Biggest take away on this one is that tags are not getting applied to articles. It probably has to do with tags from legacy platform are not present on the new taxonomy doc, but want to confirm that we were going to support those in some way. Need to figure out if we update them to the taxonomy doc and introduce them as a separate category of sorts

**Comment by davidnuescheler** [comment]
i can see all those links and they see to go the correct destination, can you check @avanishgandhi

**Comment by kptdobe** [comment]
I compared links between https://blog.adobe.com/en/2020/06/23/business-australia-relaunches-just-in-time-to-help-businesses-cope-during-covid-19.html#gs.bkqhf5 and original https://theblog.adobe.com/business-australia-relaunches-just-in-time-to-help-businesses-cope-during-covid-19: they are exactly the sames.
Maybe a caching issue in @avanishgandhi's browser ?

**Comment by avanishgandhi** [comment]
thanks for confirmation. I will send it back for testing.

**Comment by rofe** [comment]
Closing.
