### ISSUE TITLE
Add new Google site verification meta tag on blog templates

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#309]
There is a request from SEO team to add the following meta tag to the blogs template. This is a unique ID which they created for blog.adobe.com

<meta name="google-site-verification" content="VfGWzOLDyrmGv8t-bb5sGqNb8fyIhHvgC7cfRSBeKSw" />

**Comment by rofe** [comment]
@davidnuescheler do you have more context here? we already include a `google-site-verification` meta tag (identical to theblog.adobe.com), but of course we can change it or add a new one if needed.
