### ISSUE TITLE
DOTCOM-25919 - Images not displaying properly/broken

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#312]
**JIRA**  

- https://jira.corp.adobe.com/browse/DOTCOM-25919?src=confmacro
- https://jira.corp.adobe.com/browse/DOTCOM-26000?src=confmacro
- https://jira.corp.adobe.com/browse/DOTCOM-25999?src=confmacro

**Detailed Description:**
................................
**URL**: https://blog.adobe.com/en/2017/05/17/free-indesign-magazine-templates.html
................................
**Steps to Reproduce:**
1. Click on above link.
2. Note four broken links.
 
**Expected Results**: Images to display properly
................................
**Actual Results**: Broken

**Comment by rofe** [comment]
Two more articles with broken images (taken from the related issues above):
- https://blog.adobe.com/en/2017/06/01/designing-for-different-screens-and-devices-7-steps-to-creating-a-great-ux.html
- https://blog.adobe.com/en/2017/10/27/a-comprehensive-guide-to-ux-research-methods.html

**Comment by rofe** [comment]
Triggered re-imports for the ones still broken.

**Comment by rofe** [comment]
All articles above have been fixed.
