### ISSUE TITLE
4 asterisks are appearing where they should not

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#313]
**JIRA** - https://jira.corp.adobe.com/browse/DOTCOM-25916?src=confmacro

**Detailed Description:**
................................
**URL**: https://blog.adobe.com/en/2018/05/16/top-25-typefaces-next-project.html
................................
**Steps to Reproduce:**
1. Four asterisks (****) appear at the end of multiple headings

**Expected Results**: no asterisks
................................
**Actual Results:** no asterisks

**Comment by rofe** [comment]
I can no longer reproduce this. Closing.
