### ISSUE TITLE
DOTCOM-25970 - in texts links lead to 404 (wrong link are rendered)

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#314]
**JIRA** - https://jira.corp.adobe.com/browse/DOTCOM-25970?src=confmacro

**Detailed Description:**
................................
**URL**:https://theblog.adobe.com/five-ways-make-sure-distributors-love-benefits-brand-portals-manufacturer-distributor-relationships/

https://blog.adobe.com/five-ways-make-sure-distributors-love-benefits-brand-portals-manufacturer-distributor-relationships/

**The link goes to a wrong URL** - https://blog.adobe.com/en/2017/06/06/www.adobe.com/marketing/target/product-recommendations.html which seems to be common to this URL

................................
**Steps to Reproduce:**
1. click on digital asset management and product recommendations in text
Expected Results:

**Links go to new page**
................................DOTCOM-25302
Actual Results:

404 error

**Comment by rofe** [comment]
The links are wrong in the content: they are missing the `https://` prefix and are therefore (correctly) treated as relative URLs by the browser... 

Interestingly, the original blog post has a class `auto-replaced` on the anchor tag, so I assume WP auto-corrects such incomplete URLs on the fly, but I wouldn't recommend doing that. Depending on how common they are, I think we should fix them directly in the content. For future posts, we could try to detect and auto-correct them in the [importer](https://github.com/adobe/helix-theblog-importer/).

cc @kptdobe @davidnuescheler

**Comment by rofe** [comment]
Fixed the 2 broken links in the content and added an enhancement request to the importer project. Closing.

**Comment by rofe** [comment]
Reopening after talking to @davidnuescheler: we will (also) fix them on the client side.

**Comment by trieloff** [comment]
@rofe should the detection of "likely links" be something done in the pipeline? e.g.

```markdown 
[Example](www.example.com)
```

becomes

```html
<a href=www.example.com" data-likely-href="https://www.example.com">Example</a>
```

so that we can override the `href` with `data-likely-href` either in `helix-markup.yaml` or in a short client-side script?

**Comment by rofe** [comment]
> should the detection of "likely links" be something done in the pipeline?

I think that would be a nice feature.

**Comment by rofe** [comment]
Although in theblog, we can be "dumb" and always assume absolute URLs, whereas in the pipeline, we'll need to be smarter and account for all kinds of link types.
