### ISSUE TITLE
DOTCOM-25964 - Instagram content not embedding

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#315]
https://jira.corp.adobe.com/browse/DOTCOM-25964?src=confmacro

This is a feature ask rather then a bug. Looks like there is rich content on IG which we need to support.

**Detailed Description:** Embedded Instagram posts from old blog are not embedding on new post. Instead, a linked sentence is in its place saying "View this post on Instagram"
................................
**URL**: https://blog.adobe.com/en/2018/01/18/create-coloring-book-family-photos.html#gs.bbwx8c
................................
**Steps to Reproduce:**
1. Load URL
2. Scroll to see linked sentences instead of Instagram posts
Expected Results: Instagram posts will be inside the blog post
................................
**Actual Results:** Only links to instagram exist in blog post

**Comment by MarquiseRosier** [comment]
This is already supported! It should work now :)

https://blog.adobe.com/en/2018/01/18/create-coloring-book-family-photos.html#gs.c4fh7r

**Comment by rofe** [comment]
I can confirm this is working for me as well. Closing.
