### ISSUE TITLE
Redirects - Support new redirects requested from business

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#316]
I have created a new redirects.xls in the root which contains the redirects request from business

https://adobe.sharepoint.com/:x:/r/sites/TheBlog/Shared%20Documents/theblog/redirects.xlsx?d=wb20ba4a8504040daa19cbad381543fb6&csf=1&web=1&e=zDkejf

**Comment by rofe** [comment]
@trieloff can you please build the Fastly config around that?

cc @davidnuescheler

**Comment by trieloff** [comment]
See adobe/helix-dispatch#315 - this will become live updatable.
