### ISSUE TITLE
DOTCOM-26023 - Missing Videos (Vimeo video support) 

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#323]
https://jira.corp.adobe.com/browse/DOTCOM-26023?src=confmacro

Detailed Description:

This post is missing 2 embedded videos. Both of them are on Vimeo
................................
URL: https://blog.adobe.com/en/2015/11/23/the-rise-of-experiential-design-what-you-need-to-succeed.html
Original URL - https://theblog.adobe.com/the-rise-of-experiential-design-what-you-need-to-succeed/
................................
Steps to Reproduce:
1. Open URL
2. View Screenshots for locations of needed videos
3.
Expected Results:

Allow readers to view videos.
................................
Actual Results:

**Comment by rofe** [comment]
@MarquiseRosier could you check if the URL needs whitelisting?

**Comment by MarquiseRosier** [comment]
Fixed! Thanks for pointing this out @avanishgandhi and @rofe
