### ISSUE TITLE
Cards and Buttons: Design touchup

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#334]
![Screenshot 2020-08-06 at 22 28 50](https://user-images.githubusercontent.com/1609742/89579972-f5aee400-d834-11ea-9236-5235d8e3e605.png)

![Screenshot 2020-08-06 at 22 30 26](https://user-images.githubusercontent.com/1609742/89579986-fa739800-d834-11ea-8572-3e225d252144.png)

![Screenshot 2020-08-06 at 22 33 29](https://user-images.githubusercontent.com/1609742/89579995-fe071f00-d834-11ea-82b1-1b4422156e29.png)

![Screenshot 2020-08-06 at 22 28 32](https://user-images.githubusercontent.com/1609742/89580007-02333c80-d835-11ea-85db-dbf72cb91a26.png)

**Comment by rofe** [comment]
- Buttons: done
- Card widths: those are tricky, because they're calculated based on window width. If not a blocker, I'd leave them as is
- Weirdly truncated texts: caused by non-standard `--webkit-line-clamp` CSS property; works nicely on desktop browsers where text is truncated with an ellipsis at the end, but mobile browsers seem to have a weird implementation where words get cut out from the middle of the text... I see 3 solutions:
  1. Leave as is
  2. Use a more standard approach, i.e. `{ overflow: hidden; text-overflow:ellipsis; max-height: 3rem; }`. The downside is that the ellipsis isn't always rendered, which can leave a text cut off mid-sentence.
  3. Use a mixed approach: standard overflow handling on mobile and tablet, and line clamping on desktop only

@davidnuescheler wdyt?

**Comment by davidnuescheler** [comment]
i would do (i) for now. i think this is something that we should look into after `batch-1`

**Comment by rofe** [comment]
@avanishgandhi you wanted to create a follow up issue for the card widths...
