### ISSUE TITLE
Atom feed

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#344]
The legacy blog has an atom feed (https://theblog.adobe.com/feed) which is used to syndicate content on other Adobe web properties. The new blog should have one, too.

**Comment by rofe** [comment]
@trieloff I'm trying to add a `feed.xml` to theblog following https://github.com/adobe/helix-pages/blob/ea92461dd24b6ff50f1714c22312a7b2f130339e/docs/feed.md#how-to-add-an-atom-feed-to-your-helix-pages-website, but I don't quite understand what to do about the URL params in the ESI include: `id`, `title` and `updated` - shouldn't these be dynamic?

**Comment by trieloff** [comment]
You can take the parameters as they are from my example. I used `theblog`'s index as a starting point. Iy your index looks different, you can change the parameters, e.g. `updated=pubDate`

**Comment by rofe** [comment]
Implemented with #343
