### ISSUE TITLE
Articles with a future publication date should never be visible

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#351]
Create new folder under `/en/publish` with a futuristic date
Create a new post entry in that folder
Reload the homepage
-> the post entry appears on the homepage

Future posts should never appear.

Since we only store "dates" (YYYY/MM/DD) with no time, we should at least make sure that a surfer cannot see a post with DD+1, independently of the time. Which also means that people in Japan will be able to access the content before the people in the US.

**Comment by kptdobe** [comment]
Current implementation breaks too much stuff (query-index pagination, "Load more articles" button...). Reverting comming.

**Comment by davidnuescheler** [comment]
i added this to the index filtering in `query-index.xlsx` feel free to adjust if needed. i think having this implemented on the server side is safer.

**Comment by rofe** [comment]
Confirmed working by @dominique-pfister.
