### ISSUE TITLE
Articles have no author (none provided in the source document)

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/theblog#353]
During an audit of our index, I discovered that the following posts have no author, because the source document contains just `by` without an author name following:
- en/publish/2009/06/22/measuring-logged-in-visitors-without-cookies.html
- en/publish/2013/11/20/the-senate-steps-up-on-patent-reform.html
- en/publish/2013/11/21/one-giant-step-forward-on-patent-reform.html
- en/publish/2013/12/05/a-victory-in-the-house.html
- en/publish/2014/05/27/the-last-days-of-patent-reform.html
- en/publish/2016/03/09/patent-reform-is-within-grasp.html
- en/publish/2016/08/22/certiport-announces-2016-adobe-certified-associate-world-champions.html
- en/publish/2016/10/12/creating-digital-learning-content-to-create-more-successful-students.html
- en/publish/2017/01/24/expand-your-students-creativity-through-adobe-apps-now-on-chromebook.html
- en/publish/2017/03/29/skill-based-certifications-are-the-key-to-employment-for-the-next-generation.html
- en/publish/2017/09/07/adobe-education-blog-post-nmc-strategic-brief-part-2.html
- en/publish/2017/09/08/introducing-a-free-practical-guide-to-creating-digital-media-in-any-academic-discipline.html
- en/publish/2017/09/13/adobe-max-conference-contest-for-adobe-students.html
- en/publish/2017/10/13/preparing-students-for-the-digital-future.html
- en/publish/2017/10/27/vincent-fu-bringing-creativity-to-the-workplace.html

**Comment by rofe** [comment]
@avanishgandhi Maybe there's a default author we should use in such cases, i.e. _Adobe Communications Team_?

**Comment by avanishgandhi** [comment]
I am asking Matt and Giselle about this. We can have an anonymous or Adobe blog comms team as an author or maybe it Giselle

**Comment by rofe** [comment]
@avanishgandhi the current fallback is to just not display anything, but fail gracefully.
