### ISSUE TITLE
Age header should be suppressed

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/theblog#357]
currently we still respond from the outer CDN to the browser with the `age` header indicating the age of our cache. as soon as the the `age` is greater than the `max-age` header we send to the client the browser cache is considered invalid. this results in potential performance degradation particularly for resources that are shared across a lot of pages (css, js, json, etc.)

i don't think there is any need or value to send the age header from the outerCDN to the client, as a matter of fact i think it is undesirable at least for this particular usecase, so my recommendation is to strip the age header from the outer CDN response for now.

**Comment by trieloff** [comment]
Activated in v85
