### ISSUE TITLE
"Create Inspiration & Trends" topic: text is cut on the cards

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#362]
Open https://blog.adobe.com/en/topics/creative-inspiration--trends.html
Most of the cards show `CREATIVE INSPIRATION &` while I would expect to see `CREATIVE INSPIRATION & TRENDS`

**Comment by rofe** [comment]
I think the design didn't specify what should happen if the topic spilled over to a second or third line, so I may have just clamped the text at line 1...

**Comment by rofe** [comment]
After playing around with it some more, I realized we need design guidance here...
If we allow the topic to grow to 2 lines while keeping the 3 lines for the title, what can happen is this:
![image](https://user-images.githubusercontent.com/1609742/90267193-8600b080-de55-11ea-8eff-85d0e47e38e7.png)
Clamping the title after 2 lines would make it right again:
![image](https://user-images.githubusercontent.com/1609742/90267361-b6484f00-de55-11ea-9027-ae04ed75d74c.png)
But I would argue the title is the more important piece of information...

**Comment by rofe** [comment]
Design recommendation is to increase the card height to make room for a potential 2nd line for the topic title:
![image](https://user-images.githubusercontent.com/1609742/90291725-cc1f3980-de80-11ea-9a73-cfa56867dc63.png)
