### ISSUE TITLE
Add Product filters to following Topic pages

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#365]
Add Product filters to all topic pages except for list of topics under Adobe Life

- https://blog.adobe.com/en/topics/adobe-culture.html
- https://blog.adobe.com/en/topics/employee-impact.html
- https://blog.adobe.com/en/topics/university-interns.html
- https://blog.adobe.com/en/topics/career-advice.html

Giselle is going to provide some product topic pages where the filter should also not show up.

**Comment by rofe** [comment]
@avanishgandhi this is a content change, no code changed involved: just add `/components/filters.html` on its own line inside the topic source document. Be careful not to add any blanks before and after.

**Comment by avanishgandhi** [comment]
Is there a programmatic way to do this? Currently there are only 4 topics which dont need it. If not, i can work with Giselle to eventually have authors go and add it to all topics manually.

**Comment by kptdobe** [comment]
Those are now `.docx` pages, this kind of bulk operations are not possible. You'll have to add it manually.

**Comment by rofe** [comment]
A programmatic way to address this would be to switch the default behavior, i.e. when the component is included, no filters are rendered, and by default filters are always rendered. That way the include would only have to be done in 4 documents. But for sanity I'd rename the component to `no-filters,md` in that case...

**Comment by avanishgandhi** [comment]
@rofe once we fix the filter issue, can we close this story. I have seen the filters work on pages.

**Comment by rofe** [comment]
The filter issue is fixed.
