### ISSUE TITLE
Support for subfolders in promotions

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#377]
Authors would like to use subfolders in promotions for better organisation and classification.

At the moment, promotions styling is based on the fact that promotions are children of the `promotions` folder (`.embed-internal-promotions` style). https://github.com/adobe/helix-pages/issues/408 only adds the parent folder and not the full parent tree which would break the style of promotions in subfolder. 
To achieve this would require some changes in the embed class logic.

**Comment by rofe** [comment]
@kptdobe it seems like we are already adding classes for each sub folder. Close?
