### ISSUE TITLE
Publishing: purge index JSONs every hour at *:55

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#385]
In order to allow hourly publishing of articles, we should trigger a cache purge on the surrogate key of the index source file on an hourly basis (5 minutes to) to purge all JSON segments associated.

Depends on https://github.com/adobe/helix-pages/issues/424

**Comment by dominique-pfister** [comment]
Created a Google App script project (purge-index), that purges the inner and outer CDN index pages, between *:50 and *:59 (currently executes at *:52). It. does the following:

- purges index on the inner CDN
- fetches index on the inner CDN and checks its contents
- purges index on the outer CDN
- fetches index on the outer CDN and checks its contents

The current execution does this for just 1 page (offset 0).
