### ISSUE TITLE
Links starting with `www` do not work

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#387]
https://blog.adobe.com/en/2012/02/13/predictive-analytics-and-the-digital-marketer

Check the `What is Predictive Analytics?` title and click on the link: it goes to https://blog.adobe.com/en/2012/02/13/www.adobe.com/analytics/predictive-analytics.html

which is obviously wrong.

cc @rofe

**Comment by rofe** [comment]
I thought I had fixed that 😬
