### ISSUE TITLE
[Article] embeds should have a bottom margin

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#389]
Currently the text from the next paragraph is getting uncomfortably close to the image.

See https://blog.adobe.com/en/2020/08/19/how-digital-transformation-at-a-community-college-bolsters-student-success

**Comment by rofe** [comment]
@davidnuescheler it's probably best if you tackled this one since you are aware of all the edge cases...

**Comment by rofe** [comment]
Same goes for embeds:
![image](https://user-images.githubusercontent.com/1609742/91885586-555bac00-ec88-11ea-9655-8ffe76367bc0.png)
See https://blog.adobe.com/en/2020/08/31/liliane-canvas-control-plugin-designers-with-disabilities.html

**Comment by davidnuescheler** [comment]
fixed in here: https://github.com/adobe/theblog/commit/03462190dc8723078e9c598a87a32074686ce7d7
