### ISSUE TITLE
Support hidden tags in Taxonomy doc

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#397]
**Requirements**

- There is an ask from biz team to support hiding of some tags so that they don't show up as a topic tag on the page
- During discussion on slack, there was a mention of possible use of "*" to indicate that the tag should not be added to the button of the article pages.
- The logic should also apply in the case of child tags which are added to a page and up the hierarchy of tags, if a certain level tag is marked with the "*" marker, then that tag will not be added as a clickable tag on the page.

Example - The tags under internal have some parent tags which the content team might choose to hide but they want to show the child tags as clickable tags on the article pages.

https://adobe.sharepoint.com/:w:/r/sites/TheBlog/_layouts/15/Doc.aspx?sourcedoc=%7BDB164089-F1AC-41AC-8BA6-3B4FF8D0D0AC%7D&file=_taxonomy.docx&action=default&mobileredirect=true

**Comment by kptdobe** [comment]
@avanishgandhi 2 remarks / questions:

> The tags under internal

"Internal" tags are never shown... Only the "tags" in the first section ("Blog Categories") are shown on the page. The logic you are describing would only apply here.

Here are some samples to make sure I understand it correctly:

Assuming taxonomy document contains: 

```
...
- * Insights & Inspiration
    - Creativity 
        - Photography
...
```

1. Article contains `Topics: Photography`: `Photography` and `Creativity` will appear on the page
1. Article contains `Topics: Photography, Creativity`: `Photography` and `Creativity` will appear on the page
1. Article contains `Topics: Creativity, Insights & Inspiration`: `Creativity` will appear on the page

Assuming taxonomy document contains: 

```
...
- * Insights & Inspiration
    - * Creativity 
        - Photography
...
```

1. Article contains `Topics: Photography`: `Photography` will appear on the page
1. Article contains `Topics: Photography, Creativity, Insights & Inspiration`: `Photography` will appear on the page

Assuming taxonomy document contains: (edge cases)

```
...
- * Insights & Inspiration
    - Creativity 
        - * Photography
...
```

1. Article contains `Topics: Photography`: `Creativity` will appear on the page
1. Article contains `Topics: Creativity`: `Creativity` will appear on the page
1. Article contains `Topics: Insights & Inspiration`: No tag will appear on the page

**Comment by avanishgandhi** [comment]
@kptdobe based on our discussion yesterday, 

1. we are going to support the "*" appended towards the end of the tag to annotate that a given tag is hidden from the articles. Content team will use this logic to manage whats tags are shown and whats not on the article pages
2. We want to remove the logic around internal tags not shown by default.
