### ISSUE TITLE
Product Filter - fix product filter UX

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#399]
We have identified couple of issues with the Product Filters

1. The clear button on the product filter does not work. It should clear all filters but nothing changes when we click clear.
2. The list of Products all need to be filters. Currently from the Taxonomy doc, only level 2 tags under Products become filters, but the ask to have even level 1 as filters. (example - creative cloud should be a filter option so should all the products under creative cloud)

![image](https://user-images.githubusercontent.com/62259400/91345741-b10fcc00-e794-11ea-8df7-d51aeb28be0c.png)

**Comment by rofe** [comment]
@avanishgandhi here we had to deviate a bit from the design spec... the _clear_ button inside the dropdown currently just clears the list of currently selected products in the list, but doesn't submit it yet. You still need to press _apply_ to make it happen. As opposed to the _clear all_ button next to the dropdown, which does clear all filters and submit it.

If we are going to align the behaviors of the 2 buttons, I would suggest to name them both _clear all_ for consistency.

**Comment by rofe** [comment]
On the other hand, I find two different buttons doing the same thing confusing. And I think there's value in having a button inside the dropdown to reset the current selection without submitting it...

Maybe it is just a naming issue? We could rename it to _clear selection_ or _reset selection_, wdyt?

**Comment by avanishgandhi** [comment]
I agree with you and I like "Reset"

**Comment by rofe** [comment]
@avanishgandhi Great!

I have implemented both requests as discussed in staging. Please check out https://staging--theblog--adobe.hlx.page/en/topics/news.html

**Comment by avanishgandhi** [comment]
looks good. Can we push to prod? Matt wants to add it to the News topic soon. 

thanks

**Comment by rofe** [comment]
@avanishgandhi depends on @davidnuescheler's review and merge of #401 - gotta stick to due process ;)

**Comment by avanishgandhi** [comment]
Not a problem.. sorry about the push, its not that urgent :)
