### ISSUE TITLE
Soundcloud player embed does not seems to work

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#403]
From CMO import.
Just embed: https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/857268679%3Fsecret_token%3Ds-L0YFl5jRCso&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true

This shows a link and not the embedded player.

@MarquiseRosier any idea why ?

**Comment by rofe** [comment]
@MarquiseRosier any update on this?

**Comment by MarquiseRosier** [comment]
Closing this, there's not been an ask; and including it in the list of supported embeds is superfluous.
