### ISSUE TITLE
"article:tag" meta does not contain the parent topics and products

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#410]
"article:tag" meta contains the list of topics and products stored in the article but does not make use of the taxonomy to add the parents as we do in the UI.

https://github.com/adobe/theblog/blob/master/scripts/post.js#L101-L115

**Comment by avanishgandhi** [comment]
@kptdobe - from our call on 8/3, we are not planning to support * to hide tags in the product and industries filters. So we don't need to provide additional logic for these sections in the taxonomy doc.

**Comment by kptdobe** [comment]
@avanishgandhi you comment is related to https://github.com/adobe/theblog/issues/397 issue, not this one!

**Comment by rofe** [comment]
@kptdobe I think this is implemented. Closing.
