### ISSUE TITLE
Promotions render as homepage

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#411]
Open a promotion: https://blog.adobe.com/en/promotions/watch-adobe-max.html
It renders as the homepage. We should have a dedicated page that would make it render like in a page that embeds it.

**Comment by rofe** [comment]
Is this really necessary? As a workaround, you can load it with the `embed` selector:
https://blog.adobe.com/en/promotions/watch-adobe-max.embed.html

**Comment by avanishgandhi** [comment]
Is that page linked from a promotion on a page? 
the page should probably look more like a topic page then a homepage, but i don't understand why this is a bug?

**Comment by rofe** [comment]
@avanishgandhi no, promotion "pages" aren't linked anywhere publicly, you have to manually enter the URL of a promotion (or use the _Preview_ bookmarklet). It can be considered a bug because it doesn't show you the actual content you would expect to see. That can only be seen when adding a `embed` or `plain` selector before the `.html` extension.

**Comment by rofe** [comment]
I added a UI for previewing and publishing promotions:
https://staging--theblog--adobe.hlx.page/en/promotions/products/creative-cloud/premiere-pro-user-guide.html

The documentation has been updated here:
https://theblog--adobe.hlx.page/en/documentation/Production%20team/admin-managing-promotions.html

**Comment by kptdobe** [comment]
@rofe Would be cool if the Sidekick would also allow to switch from "Edit to Preview" (not tested and "Preview to Edit" (tested, no Edit button in Sidekick) for promotions. Would make authors life easy.

**Comment by rofe** [comment]
This is working as expected, but you need a staging sidekick config to test it on the `staging` branch:
https://www.hlx.page/tools/sidekick/?giturl=https%3A%2F%2Fgithub.com%2Fadobe%2Ftheblog%2Ftree%2Fstaging
