### ISSUE TITLE
indexing config: if there are no topics, indexer confuses teaser with topics

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#414]
In today's 6AM push, I noticed [one of the articles](https://blog.adobe.com/en/2020/09/02/introducing-the-2020-adobe-rising-stars-of-photography.html) had a weird looking card on the homepage: instead of the topic above the title, it was showing the first few words from the article body (aka the teaser), and instead of a teaser below the title it showed `0`.

**Comment by rofe** [comment]
@dominique-pfister could this still happen with the new indexer?

**Comment by dominique-pfister** [comment]
I'd say no: the old and the new indexer, when running side-by-side, had one article indexed differently, which happened exactly to have its teaser flow into the topics in the old index.

**Comment by rofe** [comment]
Perfect!
