### ISSUE TITLE
Canonical Tag show "/publish" folder

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#432]
Issue:- Current Blog article pages have a canonical metadata which shows a different URL from the one which is on the live pages. The metadata property shows "publish" in the path which we want to hide like we hide in the article page URLs.

![image](https://user-images.githubusercontent.com/62259400/93395321-8ad8cb80-f82a-11ea-9f5f-2294007f06ec.png)

@rofe

**Comment by rofe** [comment]
@avanishgandhi as explained last week, the canonical is correct and matches what is reported by sitemap.xml. Consider the URL without "/publish" folder (as well as the one without ".html" extension") as aliases or vanity URLs for the same content.
