### ISSUE TITLE
New metadata on blog article pages for internal search engine 

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#437]
**Background**
- USSE classifies content from all different a.com, helpx, blogs, exchange into different content type categories.
- the content type categorization is exposed on pages which get indexed by USSE
- for Blog article pages, we need to add the following metadata value so USSE knows that the content needs to get classified into Blogs content category.

**Requirement**
- Please add <meta name="serp-content-type" content="blog"> in the markup for **article, category and author** pages. 
- USSE will index the category and then make it available for us to search against this category to create a blogs only search results pages.
- Sample - View sources on https://blogs.adobe.com/creative/  and search for "serp-content-type"

**Comment by rofe** [comment]
@avanishgandhi is there a spec somewhere explaining possible values for `serp-content-type`? If there are different values, can the tag be added on the client side or does it already have to be in the initial markup?

Looking at https://blogs.adobe.com/creative/ I see `<meta name="serp-content-type" content="blog">`on all page types: article, author and category. Can you confirm that's what's expected for https://blog.adobe.com?

**Comment by rofe** [comment]
This change is in staging now: https://staging--theblog--adobe.hlx.page/
