### ISSUE TITLE
Products Tags not showing up on the articles

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#438]
- Business wants the Product tags to show-up on the article pages as a tag which users can click on.
- Currently Product tags are not showing up on the article page even when the articles were tagged with those in MD/docx files.
- Product tags in Taxonomy doc dont have * next to it so they are user facing tags.

@kptdobe @rofe

**Comment by rofe** [comment]
This was implemented as spec'd in #211:
> Products are not displayed or linked

So technically, it's an enhancement, not a bug 😉

**Comment by rofe** [comment]
Test URL: https://product-tags--theblog--adobe.hlx.page/en/publish/2020/09/24/a-new-world-shaping-new-breed-of-creative.html (should display a "Stock" tag)

**Comment by avanishgandhi** [comment]
It works. thanks
