### ISSUE TITLE
Route Algolia Queries through CDN

### ISSUE THREAD

**Issue by trieloff** [adobe/theblog#44]
This is somewhat related #42 but more cosmetic. We can modify the algoliasearch hosts.read property to use the current host and then pass the results through Fastly in the backend.

**Comment by rofe** [comment]
Can this already be implemented in theblog?

**Comment by trieloff** [comment]
It depends on https://github.com/adobe/helix-cli/pull/1279 and we'd have to copy the `helix-index.yaml` over to the `helix-pages` repository, but in general, yes.

**Comment by rofe** [comment]
I think this has been resolved.

**Comment by trieloff** [comment]
Are you sure?

**Comment by rofe** [comment]
Nope, you're right 😄

**Comment by rofe** [comment]
Closing
