### ISSUE TITLE
Interlink feature update - do not internlink specific articles

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#467]
**Requirements**

- Biz team want a way to exclude articles from getting interlinked
- David & Matt had a conversation about the ask and there was a possible solution discussed to add something to the article doc which says don't interlink.

@kptdobe @rofe

**Comment by rofe** [comment]
@avanishgandhi the proposed solution is to use an internal tag. I can look into it. Meanwhile you can pick a name for the tag 😉

**Comment by avanishgandhi** [comment]
@rofe sorry i missed this message. Did you pick a name (i trust your choice :) )

**Comment by rofe** [comment]
@avanishgandhi yes, it's `no-interlinks` for now 😉
