### ISSUE TITLE
Documents reporting errors after CMO import

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/theblog#476]
There are 2 CMO articles that show permanent errors:

- ##### `en/publish/2016/10/08/content-marketing-let's-not-mess-this-one-up.html`

  shows a 403, probably because the apostrophe is rejected by our url block list

- ##### `en/publish/2019/05/07/adobe-summit-emea-2019.html`

  shows a 500, and the error cause is the following exception:
```
Exception during #16/use:html from /nodejsAction/KUMO2xpR/html.js:237146:
InvalidCharacterError: \"data-Thousands of experience-minded marketers from across Europe have converged in
London this week for the annual Adobe Summit—The Digital Experience Conference. Among the topics\" did not
match the Name production: Unexpected syntax in top
Line 1:
data-Thousands of experience-minded marketers from across Europe have converged in London this week for the
annual Adobe Summit—The Digital Experience Conference. Among the topics
             ^^^
```

/cc: @kptdobe

**Comment by dominique-pfister** [comment]
first problem resolved, apostrophe was removed

**Comment by rofe** [comment]
second problem solved as well, added additional line break before body text as a workaround for https://github.com/adobe/helix-pipeline/issues/876
