### ISSUE TITLE
FEDS header spacing at the bottom

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#479]
Since the blue info banner is gone, there seems to be excess spacing at the bottom of the FEDS header. It is noticeable on topic pages where the banner image should start right underneath the FEDS header:
https://blog.adobe.com/en/topics/cmo-by-adobe.html

**Comment by rofe** [comment]
It's from a height property set directly on the element:
```html
<div class="feds-topnav-spacing" style="height: 80px;"></div>
```

**Comment by rofe** [comment]
Fwiw, it's `60px` on adobe.com...

**Comment by narcis-radu** [comment]
Web Production will fix the issue, there's already a ticket for it - DOTCOM-31670
cc @avanishgandhi

**Comment by avanishgandhi** [comment]
@rofe @narcis-radu Dan has updates the experiences.

**Comment by rofe** [comment]
@narcis-radu, @avanishgandhi I can confirm that the excess spacing is gone.
