### ISSUE TITLE
[Topic page] "No articles..." message not visible when category is really empty

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#484]
https://theblog--adobe.hlx.page/en/topics/_test.html

No article with this category, the "No articles..." message is in the DOM but hidden, nothing "turns it on".

@davidnuescheler @rofe I tried to fix this but the overall logic is pretty mysterious...

**Comment by rofe** [comment]
I can take a look at it.

**Comment by rofe** [comment]
Looks like a CSS problem

**Comment by kptdobe** [comment]
Yes, it is set to `visibility:hidden` by default but never set to visible!

**Comment by rofe** [comment]
Right. Probably a regression from #430
