### ISSUE TITLE
Publishing: Google App script to also purge theblog--adobe.hlx.live

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#492]
Extend the Google App script to also purge `theblog--adobe.hlx.live` (alternate hostname for outer CDN).

**Comment by dominique-pfister** [comment]
Hm, I don't think it's possible to spend considerable more time in that Google App script, as it already scratches at the 5 minutes max-duration limit.

**Comment by rofe** [comment]
Note that we won't need to re-fetch any segments on the outermost CDN, as it will have a fast outer CDN as its backend:

```
        Inner CDN       >        Outer CDN        >     Proxy
theblog--adobe.hlx.page   theblog--adobe.hlx.live   blog.adobe.com
```

So like today, we'd first purge and re-fetch from the inner CDN, then purge/re-fetch on the outer CDN. As a last step, we'd purge blog.adobe.com without re-fetching.

If that will take us over the 5 minute mark, we'll need to think about a different solution. Maybe 2 separate scripts? Re-fetch less segments on the inner CDN?

**Comment by rofe** [comment]
@dominique-pfister it would be great if you could start implementing this.

**Comment by dominique-pfister** [comment]
If I understand that correctly, I just need to replace:
```
- const OUTER_CDN = 'blog.adobe.com';
+ const OUTER_CDN = 'theblog--adobe.hlx.live';
```
in the script, right?

**Comment by rofe** [comment]
That's the first part, yes. But you also need to purge blog.adobe.com, at first including re-fetching because it will be the same service with the same backend (inner CDN). Once blog.adobe.com is moved to a separate service (as shown in the ascii diagram above), we can omit re-fetching on blog.adobe.com because that service will have `theblog--adobe.hlx.live` as its backend, which will have a full cache and therefore be quick enough.

**Comment by dominique-pfister** [comment]
Done, I modified the Google Apps Script to run with a CDN configuration, here are the details:
```
/**
 * New CDN configuration (with Skyline CDN in front).
 */
const NEW_CDN_CONFIG = [{
    name:  'Helix-Inner',
    host:  'theblog--adobe.hlx.page',
    fetch:  -1, /* re-fetch all pages after purging */
    verify: 10, /* verify that many pages */
    token: 'INNER_FASTLY_TOKEN',
  }, {
    name:  'Helix-Outer',
    host:  'theblog--adobe.hlx.live',
    fetch:  20, /* re-fetch only that many pages after purging */
    token:  'OUTER_FASTLY_TOKEN',
  }, {
    name:  'Skyline',
    host:  'blog.adobe.com',
    fetch:  0,  /* re-fetch no pages at all */
}];

/**
 * Old CDN configuration.
 */
const OLD_CDN_CONFIG = [{
    name:  'Helix-Inner',
    host:  'theblog--adobe.hlx.page',
    fetch:  -1, /* re-fetch all pages after purging */
    verify: 10, /* verify that many pages */
    token:  'INNER_FASTLY_TOKEN',
  }, {
    name:   'Helix-Outer',
    host:   'blog.adobe.com',
    fetch:   10, /* re-fetch only that many pages after purging */
    token:   'OUTER_FASTLY_TOKEN',
}];
```
It currently uses `OLD_CDN_CONFIG` and as soon as we're ready to switch we change it to use `NEW_CDN_CONFIG`.
