### ISSUE TITLE
Set surrogate cache headers on outer CDN

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#493]
We want downstream proxies to only cache for a short time instead of the same (very long) duration as the outer CDN, so when new content gets published and the outer CDN cache is purged, the changes will become available with a short delay.

**Comment by rofe** [comment]
Discussed with @davidnuescheler: a proxy between the blog outer CDN and the browser should ideally not cache at all or use the browser cache instructions.

**Comment by stefan-guggisberg** [comment]
@davidnuescheler How long exactly should a downstream proxy cache? Should there be separate policy for `/hlx_*` resources?

**Comment by stefan-guggisberg** [comment]
> Should there be separate policy for /hlx_* resources?

Probably not. If we can't control the downstream proxy we wouldn't want e.g. broken images (502,503,504) being cached for a longer period by the downstream proxy.

**Comment by davidnuescheler** [comment]
i think generally immutable resources should probably be cached by the outercdn for an extensive period of time.
i generally think that the `max-age` could initially serve as a good indication and probably is used by the outercdn implicitly. considering that in the case of skyline we can purge invalidate i think we should be fine with using the browser cache control headers in the skyline cdn should be a good starting point.

**Comment by davidnuescheler** [comment]
also, for a skyline cdn, we should generally assume that we can control (eg. push invalidate) the cache.

**Comment by stefan-guggisberg** [comment]
Ok. Just to confirm: We don't need to do change anything. The outer CDN (`hlx.live`) currently delivers resources in general with `Cache-Control: max-age=7200, must-revalidate` and immutable resources (like images) with `Cache-Control: max-age=31536000`. The Fastly downstream proxy (skyline) interprets these as caching instructions. 

Right?

**Comment by davidnuescheler** [comment]
that sounds good to me for now. i think we can assume that we can push invalidate the skyline cdn and therefore those settings are fine.

**Comment by rofe** [comment]
I can confirm that (at least for now) push invalidation through all 3 CDNs works. Closing this issue again.
