### ISSUE TITLE
Cleanup the icon folder

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#496]
Apart from https://github.com/adobe/theblog/blob/master/icons/adobe.svg, does someone use icons ? I doubt since most of them are outdated or even wrong like: 
- https://github.com/adobe/theblog/blob/master/icons/creativecloud.svg
- https://github.com/adobe/theblog/blob/master/icons/creative-cloud.svg

Probably bug in the importer...

I think we can remove most of them.

@rofe @davidnuescheler WDYT ?

**Comment by elaineskpt** [comment]
The PR for this one was already opened last week https://github.com/adobe/theblog/pull/642
