### ISSUE TITLE
Support for new Landing page designs

### ISSUE THREAD

**Issue by avanishgandhi** [adobe/theblog#545]
- Ask is to support new designs for landing pages like MAX and Summit which are not homepages, but need to be more engaging then the current Category pages

XD - https://xd.adobe.com/view/531ae868-1a2c-4c0f-ade5-b1ca33c1110e-0649/ 
JIRA Story - https://jira.corp.adobe.com/browse/DOTCOM-30951 

@rofe This is something Matt and Giselle confirmed is the new designs they are targeting. Please let us know if we need to meet Studio team to walk us through the ask

**Comment by rofe** [comment]
@avanishgandhi what happens if there is no featured article defined? Will the template always use the most recent one (like the homepage)? Otherwise, we'll need design specs for this case.

**Comment by avanishgandhi** [comment]
@rofe how would authors choose a page to have landing page transformation? 
We have 3 types of pages (templates)
- Home Page
- Landing Pages (this is the new type which we are trying to build)
- Category/topic Pages (all the category pages that dont need special treatment)

I would say that if an Author chooses to use landing page transformation then they need to have a featured article (or we use the latest article published to be featured by default)

**Comment by rofe** [comment]
@avanishgandhi all pages under `/{lang}/topics` will be category/topic pages. I am thinking of this new design as a special capability of the topic page. If not all topic pages should receive it, I could see two possibilities to handle this on the authoring side:
1. we could make _landing-page_ a drop-in component, like _filters_. If present, the topic page will become a landing page and render a featured article. 
    1. if no featured article is specified, it will use the most recent article
    1. if no featured article is specified, it will fall back to a normal topic page 
1. if a topic page has a featured article in the content, the topic page will be transformed into a landing page.

Which would you prefer? For the sake of simplicity I am personally leaning towards (2); I think it is more intuitive and there is no ambiguity as to which article to render as featured article.

**Comment by avanishgandhi** [comment]
2 sounds the easiest one to me. If that works, lets go with that

**Comment by rofe** [comment]
Like on homepages and articles, authors can now add a _Featured Posts_ section to the docx to transform a topic page into a landing page, for example:

<pre>---</pre>

<h2>Featured Posts</h2>

- https://blog.adobe.com/en/publish/2020/12/07/consumer-behavior-trends-digital-economy.html 

@avanishgandhi
