### ISSUE TITLE
Sidekick: show article tags when opening tagger

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#547]
Use case: as an author, I want to add one tag to the list of tags (like the `UK` tag).
Today, this can be achieved with:
- re-generate the list of tags in the tagger + add the corresponding tag (high risk to miss one)
- copy the  `Topics / Products` block in the Word document, paste it into the tagger, add the tag, "copy" the tags and override the `Topics / Products` block with the new list (secret advanced copy/paste feature)

To make it a little bit more simple (still not perfect), my proposal is: when you click on the "Tagger" button in the sidekick from an article, it pre-loads the tags in the tagger. This can be easily achieved by passing the article's topics and products in the url and read them in the tagger. This would already a by step forward to add one single tag.

@rofe WDYT ?

**Comment by rofe** [comment]
I think this would be great, but so far I haven't found a way to access the content iframe from the outer window. It is blocked by CSP.

**Comment by rofe** [comment]
Not feasible at the moment.
