### ISSUE TITLE
[Import] inject the original canonical url

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#555]
As part of the migration from blogs.adobe.com to blog.adobe.com and to be able to avoid SEO penalty for duplicated content, we need to store the original canonical url of each imported articles. 

Proposal is to add 2 frontmatter properties: 
- `canonicalOverrideURL`: url of the original article on blogs.adobe.com
- `canonicalOverrideCutoff`: @trieloff can you specify what would this date be for ?

We also need to determine where to store this information in the md / docx files, knowing we'll have more metadata coming (like `description`, see #544) and we might need to adjust the site client side code to handle pages with and without those metadata. We also need to keep in mind authoring simplicity.

cc @rofe @davidnuescheler

**Comment by trieloff** [comment]
`canonicalOverrideCutoff`: we plan to switch the URLs from blogs.adobe.com to blog.adobe.com sometime early March. To avoid having to reindex things, we add a `canonicalOverrideCutoff=March 0x, 2021` property to each import. The renderer would ignore the `canonicalOverrideURL` after that date.

If we take the client-side approach suggested by @rofe we won't need this property as we can do a simple code push.

**Comment by kptdobe** [comment]
The `canonicalOverrideURL` trick would only necessary if `blogs.adobe.com/old/path/to/article` and `blog.adobe.com/new/path/to/article` would live at the same time. Which may happen but for a so short period of time that it is even not sure Google would have time to see it.
We then decided to NOT implement the `canonicalOverrideURL` trick.
