### ISSUE TITLE
Override the canonical url with the original canonical url

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#556]
Once the imported articles will store the original url (see #555), we need to override the current canonical url by this "original url".
The current proposal is to do it client side for each article which has the `canonicalOverrideURL` property.

cc @rofe @trieloff

**Comment by rofe** [comment]
Do you have the spec how this would look in markup?

**Comment by kptdobe** [comment]
This needs to be defined in #555.

**Comment by kptdobe** [comment]
The `canonicalOverrideURL` trick would only necessary if `blogs.adobe.com/old/path/to/article` and `blog.adobe.com/new/path/to/article` would live at the same time. Which may happen but for a so short period of time that it is even not sure Google would have time to see it.
We then decided to NOT implement the `canonicalOverrideURL` trick.
