### ISSUE TITLE
Sidekick: predicted url for documentation pages is wrong

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#564]
- Navigate to https://theblog--adobe.hlx.page/en/documentation/Production%20team/homepage-howto.html 
- Open the Sidekick
- Hit the "Copy Predicted URL" button

-> it copies https://blog.adobe.com/en/2020/06/30/homepage-howto.html which is wrong (should be https://blog.adobe.com/en/documentation/Production%20team/homepage-howto.html).

**Comment by rofe** [comment]
Yeah, I think the predicted URL feature should probably not be there for documentation pages...
