### ISSUE TITLE
[Posts] Simplify expected blog post markdown

### ISSUE THREAD

**Issue by kptdobe** [adobe/theblog#6]
https://github.com/davidnuescheler/theblog/blob/alexonedrive/content/posts/creating-adobe-experience-platform-pipeline-with-kafka.md starts being the "reference" markdown.

The current style implementation requires the md file to start with:
- a title
- a thematic break
- an image
- a thematic break
- the "author block"
- a thematic break
- the blog post content

All those thematic breaks are only here to properly style the fullscreen hero image and to differentiate the author section. 
This requires the author to know those requirements and will be leading to a lot of rendering errors (oups i forgot a thematic break somewhere...).

TODO 1: remove the first TB from the reference md and rewrap the dom with required divs. This should be doable with https://github.com/adobe/helix-pipeline/issues/516

But this does not solve the "what if the author does not have a hero image" or "he/she/they forgot to add  the author section"... our code has to have a strong resilience to author mistakes. This would be doable only with code...

TODO 2: make sure the layout does not break for basic author mistakes or use cases we forgot.

**Comment by rofe** [comment]
I think we can close this now as the current document structure is documented and authors trained.
