### ISSUE TITLE
switch to main branch

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/theblog#620]
let's see if we can switch our main branch to `main`. i appreciate that we might have to change some config so it is not exactly a trivial operation.

i just wanted to make sure that we keep that on our radar.

**Comment by rofe** [comment]
I think it should be a trivial change - probably the only thing that needs updating are the authors' bookmarklets.

**Comment by tripodsan** [comment]
> I think it should be a trivial change - probably the only thing that needs updating are the authors' bookmarklets.

I'm not sure.... `master` is still the default fallback branch in many services....

**Comment by rofe** [comment]
I know, but we already have projects successfully using `main`. And the sidekick helps bridge the gap.

**Comment by rofe** [comment]
Let's combine this with the switch to hlx3.
