### ISSUE TITLE
Instagram Embed is rendered wrongly on firefox

### ISSUE THREAD

**Issue by tripodsan** [adobe/theblog#658]
When adding an instagram post in an article, the text will be broken in Firefox. Chrome, Safari and Edge is no problem. Could you please check it. Thank you to your support.

https://blog.adobe.com/jp/publish/2021/04/20/cc-design-fresco-creative-relay-14-bechori.html

![image](https://user-images.githubusercontent.com/917628/115478644-8de4e000-a281-11eb-99dc-1b53827967f8.png)

**Comment by rofe** [comment]
@MarquiseRosier could you take this?

**Comment by MarquiseRosier** [comment]
Done! Fix can be observed here. Authoring guides should be updated to deprecate service embeds for Instagram, tv.adobe, YouTube, Vimeo.
