### ISSUE TITLE
Korean blog homepage - auto publish doesn't work

### ISSUE THREAD

**Issue by mattyroze** [adobe/theblog#680]
https://blog.adobe.com/ko/index.html is not auto-publishing each day. Perhaps the expected behavior?

So, the KO team is having to republish the homepage manually but that doesn't seem to be working for them and they must ask HELIX team to fix this each time.

Recommendations:
1. Setup Korean language blog home page so it manually publishes at 6am Korean time, and/or -
2. Fix the homepage publish feature so Korean team can manage that themselves without asking for help

**Comment by dominique-pfister** [comment]
Fixed 1: Korean language blog home page publishes at 6am Korean time.

**Comment by mattyroze** [comment]
Awesome. Thanks so much Dominique!

From: Dominique Pfister ***@***.***>
Reply-To: adobe/theblog ***@***.***>
Date: Thursday, May 27, 2021 at 3:56 AM
To: adobe/theblog ***@***.***>
Cc: Matt Rozen ***@***.***>, Author ***@***.***>
Subject: Re: [adobe/theblog] Korean blog homepage - auto publish doesn't work (#680)


Fixed 1: Korean language blog home page publishes at 6am Korean time.
