### ISSUE TITLE
Log a warning when topic is not found in taxonomy

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/theblog#703]
While looking at a topic that returns no articles, I noticed that the code:

https://github.com/adobe/theblog/blob/dba8b8a1770375b96c6dbb7b6fa0d501fcfdf71f/scripts/v2/common.js#L622

and lines following silently fill in an empty topic so the code keeps working for a topic that isn't found. Might be worth logging a warning (or some other indication) which would help detecting a missing topic quicker.

**Comment by kptdobe** [comment]
I would not qualify this as a "bug" but I agree!
