### ISSUE TITLE
redesign theblog to look closer to XD implementation

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/theblog#89]
- [ ] Use Algolia query to retrieve M posts based on recency and use top N to fill out responsive design; first N will be tagged and styled differently on the homepage. 
- [ ]  Implement Latest Stories section with remaining M-N posts styled differently from the latest N.

**Comment by MarquiseRosier** [comment]
@rofe @davidnuescheler I noticed you both were working on the CSS the most; so I want to definitely have your insights here

**Comment by MarquiseRosier** [comment]
https://github.com/davidnuescheler/theblog/tree/moveTopic

**Comment by rofe** [comment]
Hint: if you use a lowercase branch name, it could be previewed through Helix Pages:
https://movetopic--theblog--davidnuescheler.project-helix.page/index.html

**Comment by rofe** [comment]
Continued in #179
