### ISSUE TITLE
[Global] create custom FEDS/gnav2 experience for theblog

### ISSUE THREAD

**Issue by rofe** [adobe/theblog#91]
This is currently blocking #82 
- custom nav for header and footer
- consent management

**Comment by narcis-radu** [comment]
@rofe - region picker content and modal still have to come from Blogs/ Helix side - FEDS will just execute the method you pass in `fedsConfig.footer.regionModal`.

**Comment by avanishgandhi** [comment]
we should tag this as batch 2 requirement.

**Comment by rofe** [comment]
This is done and integrated by #236
